const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert');
const root=path.resolve(__dirname,'..');
const baseline=fs.readFileSync(path.join(root,'docs','ChatGPT NET Functional Baseline 1.3.md'),'utf8');
assert.match(baseline,/ChatGPT NET Functional Baseline 1\.3/);
assert.match(baseline,/\*\*版本：1\.3\*\*/);
const clauses=[...baseline.matchAll(/^(\d+)\.\s/gm)].map(m=>Number(m[1]));
assert.strictEqual(clauses.length,500,'baseline must contain 500 numbered clauses');
assert.deepStrictEqual(clauses,Array.from({length:500},(_,i)=>i+1),'baseline clauses must be continuous 1..500');
const sections=[...baseline.matchAll(/^# (\d+)\. /gm)].map(m=>Number(m[1]));
assert.deepStrictEqual(sections,Array.from({length:46},(_,i)=>i+1),'baseline sections must be continuous 1..46');
assert.match(baseline,/83\. [^\n]*任意两个父节点之间不得存在直接或间接的上游\/下游关系/,'clause 83 must enforce independent co-parents');
assert.match(baseline,/205\. [^\n]*最终层级图清晰[^\n]*受影响连通层级执行结构化重排/,'clause 205 must prioritize a clean result before affected-component rearrangement');
assert.match(baseline,/206\. [^\n]*不得波及无关自由节点[^\n]*移动范围更小/,'clause 206 must contain rearrangement to the affected hierarchy');
assert.ok(!fs.existsSync(path.join(root,'ChatGPT NET Functional Baseline 1.3.md')),'the baseline must have only one repository copy under docs');
assert.ok(!fs.readdirSync(path.join(root,'docs')).some(n=>/1\.2/.test(n)),'shipping docs must not retain superseded Baseline 1.2 files');
assert.ok(!fs.existsSync(path.join(root,'docs','ChatGPT NET Functional Baseline 1.4.md')),'the rejected 1.4 layout baseline must not remain current');
const baseline15=fs.readFileSync(path.join(root,'docs','ChatGPT NET Functional Baseline 1.5.md'),'utf8'),clauses15=[...baseline15.matchAll(/^(\d+)\.\s/gm)].map(m=>Number(m[1])),sections15=[...baseline15.matchAll(/^# (\d+)\. /gm)].map(m=>Number(m[1]));
assert.match(baseline15,/ChatGPT NET Functional Baseline 1\.5/);assert.deepStrictEqual(clauses15,Array.from({length:116},(_,i)=>i+1),'1.5 clauses must be continuous 1..116');assert.deepStrictEqual(sections15,Array.from({length:16},(_,i)=>i),'1.5 sections must be continuous 0..15');
assert.match(baseline15,/99\. 无关系节点拖到空白处后停在释放点或最近合法点/);assert.match(baseline15,/112\. 对话移入另一个 ChatGPT 项目并再移出时/);
const audit=fs.readFileSync(path.join(root,'docs','BASELINE_AUDIT_1.3.md'),'utf8');
const allMarkdown=fs.readdirSync(path.join(root,'docs')).filter(n=>n.endsWith('.md')).map(n=>fs.readFileSync(path.join(root,'docs',n),'utf8')).join('\n');
assert.ok(!/Firefox 140\+/.test(allMarkdown),'current documentation must not promise unsupported Firefox 140 compatibility');
assert.ok(!audit.includes('自动/自动/源码通过'),'audit status labels must not contain duplicated prefixes');
assert.match(audit,/\| 83 \|[^\n]*任意两个父节点之间不得存在直接或间接/);
assert.ok(!fs.existsSync(path.join(root,'BASELINE_AUDIT_1.3.md')),'the baseline audit must have only one repository copy under docs');
const recheck=fs.readFileSync(path.join(root,'docs','BASELINE_RECHECK_1.4.0.md'),'utf8');
const recheckChapters=[...recheck.matchAll(/^\| (\d+) \|/gm)].map(m=>Number(m[1])).filter(n=>n>0);
assert.deepStrictEqual(recheckChapters,Array.from({length:46},(_,i)=>i+1),'1.4 recheck must cover all 46 baseline chapters');
const acceptanceGroups=[...recheck.matchAll(/^\| (0|[A-R]) \|/gm)].map(m=>m[1]);
assert.deepStrictEqual(acceptanceGroups,['0',...Array.from({length:18},(_,i)=>String.fromCharCode(65+i))],'1.4 recheck must cover manual acceptance groups 0 and A-R');
const releaseNotes=fs.readFileSync(path.join(root,'docs','RELEASE_NOTES_1.4.0.md'),'utf8');
assert.match(releaseNotes,/ChatGPT NET 1\.4\.0/);
const release141=fs.readFileSync(path.join(root,'docs','RELEASE_NOTES_1.4.1.md'),'utf8'),recheck142=fs.readFileSync(path.join(root,'docs','BASELINE_RECHECK_1.4.2.md'),'utf8'),release142=fs.readFileSync(path.join(root,'docs','RELEASE_NOTES_1.4.2.md'),'utf8');
assert.match(release141,/ChatGPT NET 1\.4\.1/);assert.match(recheck142,/ChatGPT NET 1\.4\.2/);assert.match(release142,/ChatGPT NET 1\.4\.2/);
assert.deepStrictEqual([...recheck142.matchAll(/^\| (\d+) \|/gm)].map(m=>Number(m[1])).filter(n=>n>0),Array.from({length:46},(_,i)=>i+1),'1.4.2 recheck must cover all 46 chapters');
assert.deepStrictEqual([...recheck142.matchAll(/^\| (0|[A-R]) \|/gm)].map(m=>m[1]),['0',...Array.from({length:18},(_,i)=>String.fromCharCode(65+i))],'1.4.2 recheck must cover acceptance groups 0 and A-R');
const recheck143=fs.readFileSync(path.join(root,'docs','BASELINE_RECHECK_1.4.3.md'),'utf8'),release143=fs.readFileSync(path.join(root,'docs','RELEASE_NOTES_1.4.3.md'),'utf8');
assert.match(recheck143,/ChatGPT NET 1\.4\.3/);assert.match(release143,/ChatGPT NET 1\.4\.3/);
assert.deepStrictEqual([...recheck143.matchAll(/^\| (\d+) \|/gm)].map(m=>Number(m[1])).filter(n=>n>0),Array.from({length:46},(_,i)=>i+1),'1.4.3 recheck must cover all 46 chapters');
assert.deepStrictEqual([...recheck143.matchAll(/^\| (0|[A-R]) \|/gm)].map(m=>m[1]),['0',...Array.from({length:18},(_,i)=>String.fromCharCode(65+i))],'1.4.3 recheck must cover acceptance groups 0 and A-R');
const recheck144=fs.readFileSync(path.join(root,'docs','BASELINE_RECHECK_1.4.4.md'),'utf8'),release144=fs.readFileSync(path.join(root,'docs','RELEASE_NOTES_1.4.4.md'),'utf8');
assert.match(recheck144,/ChatGPT NET 1\.4\.4/);assert.match(release144,/ChatGPT NET 1\.4\.4/);
assert.deepStrictEqual([...recheck144.matchAll(/^\| (\d+) \|/gm)].map(m=>Number(m[1])).filter(n=>n>0),Array.from({length:46},(_,i)=>i+1),'1.4.4 recheck must cover all 46 chapters');
assert.deepStrictEqual([...recheck144.matchAll(/^\| (0|[A-R]) \|/gm)].map(m=>m[1]),['0',...Array.from({length:18},(_,i)=>String.fromCharCode(65+i))],'1.4.4 recheck must cover acceptance groups 0 and A-R');
const recheck145=fs.readFileSync(path.join(root,'docs','BASELINE_RECHECK_1.4.5.md'),'utf8'),release145=fs.readFileSync(path.join(root,'docs','RELEASE_NOTES_1.4.5.md'),'utf8');
assert.match(recheck145,/ChatGPT NET 1\.4\.5/);assert.match(release145,/ChatGPT NET 1\.4\.5/);
assert.deepStrictEqual([...recheck145.matchAll(/^\| (\d+) \|/gm)].map(m=>Number(m[1])).filter(n=>n>0),Array.from({length:46},(_,i)=>i+1),'1.4.5 recheck must cover all 46 chapters');
assert.deepStrictEqual([...recheck145.matchAll(/^\| (0|[A-R]) \|/gm)].map(m=>m[1]),['0',...Array.from({length:18},(_,i)=>String.fromCharCode(65+i))],'1.4.5 recheck must cover acceptance groups 0 and A-R');
const recheck146=fs.readFileSync(path.join(root,'docs','BASELINE_RECHECK_1.4.6.md'),'utf8'),release146=fs.readFileSync(path.join(root,'docs','RELEASE_NOTES_1.4.6.md'),'utf8');
assert.match(recheck146,/ChatGPT NET 1\.4\.6/);assert.match(release146,/ChatGPT NET 1\.4\.6/);
assert.deepStrictEqual([...recheck146.matchAll(/^\| (\d+) \|/gm)].map(m=>Number(m[1])).filter(n=>n>0),Array.from({length:46},(_,i)=>i+1),'1.4.6 recheck must cover all 46 chapters');
assert.deepStrictEqual([...recheck146.matchAll(/^\| (0|[A-R]) \|/gm)].map(m=>m[1]),['0',...Array.from({length:18},(_,i)=>String.fromCharCode(65+i))],'1.4.6 recheck must cover acceptance groups 0 and A-R');
const recheck150=fs.readFileSync(path.join(root,'docs','BASELINE_RECHECK_1.5.0.md'),'utf8'),release150=fs.readFileSync(path.join(root,'docs','RELEASE_NOTES_1.5.0.md'),'utf8'),manual150=fs.readFileSync(path.join(root,'docs','MANUAL_ACCEPTANCE_1.5.md'),'utf8');
assert.deepStrictEqual([...recheck150.matchAll(/^\| (\d+) \|/gm)].map(m=>Number(m[1])),Array.from({length:116},(_,i)=>i+1),'1.5.0 recheck must cover clauses 1..116');assert.match(release150,/ChatGPT NET 1\.5\.0/);assert.match(manual150,/Windows Firefox 实机验收清单/);

const manifest=JSON.parse(fs.readFileSync(path.join(root,'manifest.json'),'utf8'));
assert.strictEqual(manifest.manifest_version,3);
assert.strictEqual(manifest.name,'ChatGPT NET');
assert.strictEqual(manifest.version,'1.5.1');
assert.deepStrictEqual(manifest.permissions,['storage'],'only storage permission is required');
assert.deepStrictEqual(new Set(manifest.host_permissions),new Set(['https://chatgpt.com/*','https://chat.openai.com/*']));
assert.ok(parseFloat(manifest.browser_specific_settings.gecko.strict_min_version)>=152);
assert.ok(!manifest.content_scripts[0].js.includes('src/content/layout.js'),'the rejected whole-component layout module must not ship');
assert.ok(manifest.content_scripts[0].js.includes('src/content/hierarchy.js'),'relation hierarchy arranger must load before the application');
assert.deepStrictEqual(manifest.browser_specific_settings.gecko.data_collection_permissions.required,['none']);
assert.strictEqual(manifest.incognito,'spanning');
const pkg=JSON.parse(fs.readFileSync(path.join(root,'package.json'),'utf8'));
assert.strictEqual(pkg.type,'commonjs','project tests must be isolated from parent ESM package settings');
assert.strictEqual(pkg.version,manifest.version);
assert.match(pkg.scripts.build,/scripts\/build-extension\.ps1/);
assert.match(pkg.scripts['test:firefox'],/firefox_extension_integration\.mjs/);
assert.match(pkg.devDependencies['web-ext'],/^\d+\.\d+\.\d+$/,'Firefox package builder must use an exact version');
const packageLock=JSON.parse(fs.readFileSync(path.join(root,'package-lock.json'),'utf8'));
assert.strictEqual(packageLock.packages['node_modules/web-ext'].version,pkg.devDependencies['web-ext'],'lockfile must match the pinned Firefox builder');
const buildScript=fs.readFileSync(path.join(root,'scripts','build-extension.ps1'),'utf8');
assert.match(buildScript,/\bnpx --no-install web-ext build\b/,'package must use the pinned Firefox web-ext builder');
assert.ok(!buildScript.includes('Compress-Archive'),'PowerShell ZIPs register but fail to resolve content scripts in Firefox 152');
assert.ok(buildScript.includes('.xpi'),'build must produce a Firefox-native XPI alongside the ZIP');
for(const runtime of ['manifest.json','background.js','icons','src'])assert.ok(buildScript.includes(`'${runtime}'`),`package must include runtime path ${runtime}`);
for(const excluded of ['docs','tests','README','Functional Baseline'])assert.ok(!buildScript.includes(`'${excluded}'`),`package must exclude non-runtime path ${excluded}`);
assert.ok(!fs.existsSync(path.join(root,'ChatGPT-NET-1.3-refactor.zip')),'obsolete 1.3 package must not remain in the repository');

if(!globalThis.crypto)globalThis.crypto=require('crypto').webcrypto;
for(const f of ['src/shared/constants.js','src/shared/utils.js'])vm.runInThisContext(fs.readFileSync(path.join(root,f),'utf8'),{filename:f});
const C=globalThis.ChatGPTNET.C;
assert.deepStrictEqual([C.INITIAL_VIEW_W,C.INITIAL_VIEW_H,C.MAX_VIEW_W,C.MAX_VIEW_H,C.WORLD_W,C.WORLD_H],[360,900,720,900,2880,3600]);
assert.deepStrictEqual([C.DEFAULT_ZOOM,C.MIN_ZOOM,C.MAX_ZOOM],[.75,.25,3]);
assert.strictEqual(C.HISTORY_LIMIT,15);
assert.strictEqual(C.PRODUCT,'ChatGPT NET');
assert.strictEqual(C.BASELINE,'1.5');
assert.deepStrictEqual(C.IMPORT_BASELINES,['1.3','1.4','1.5']);
assert.strictEqual(C.STORAGE_PREFIX,'chatgpt-net:v1:');

const sourceFiles=[];
for(const dir of ['src','icons']){
  const walk=d=>{for(const ent of fs.readdirSync(d,{withFileTypes:true})){const p=path.join(d,ent.name);ent.isDirectory()?walk(p):sourceFiles.push(p);}};walk(path.join(root,dir));
}
sourceFiles.push(path.join(root,'background.js'),path.join(root,'manifest.json'));
const source=sourceFiles.filter(f=>/\.(?:js|json|css|svg)$/.test(f)).map(f=>fs.readFileSync(f,'utf8')).join('\n');
for(const forbidden of ['parentByChild','Chat Tree','适合内容','browser.webRequest','XMLHttpRequest'])assert.ok(!source.includes(forbidden),`forbidden legacy/network token: ${forbidden}`);
assert.ok(!/\bfetch\s*\(/.test(source),'extension must not fetch or modify ChatGPT network requests');
assert.ok(!/Alt[＋+]/.test(source),'no Alt shortcut may be exposed');
assert.ok(!source.includes('chat-tree:'),'legacy storage namespace must not be read');
assert.strictEqual(C.COLORS.length,3,'Baseline 1.3 exposes exactly three color slots');
const main=fs.readFileSync(path.join(root,'src/content/main.js'),'utf8'),css=fs.readFileSync(path.join(root,'src/content/styles.css'),'utf8');
assert.ok(!main.includes("add('>>'"),'page-level >> collapse button must not exist');
assert.ok(!main.includes('collapseSidebar'),'page-level collapse state must not exist');
assert.ok(!css.includes('cgn-collapsed-tab'),'page-level << recovery button must not exist');
assert.ok(main.includes("add('解除'"),'toolbar unlink button must be named 解除');
assert.ok(main.includes('collapseOnClick'),'ordinary click on one member of a multi-selection must collapse to single selection if no drag occurs');
assert.ok(!main.includes('Layout.layered')&&main.includes('findPlacementSolution(temp,ids,desired)'),'ordinary movement must preserve the bounded local-placement solver');
assert.ok(main.includes('hierarchyPlacementSolution(temp,seeds,baseRoutes=this.routes,options={})')&&main.includes('Hierarchy.arrange(temp,seeds,options)'),'relation creation must use the bounded hierarchy arranger');
assert.ok(main.includes('Hierarchy.translationCandidates(temp,layout)')&&main.includes('Router.routeHierarchy(temp,layout.ids,preferred)'),'new relations must use whole-component obstacle placement and structured-only routing');
assert.ok(main.includes('upgradeHierarchyLayout(c)')&&main.includes('manualConnectedMoveSolution(ids,desired)')&&main.includes('translatedSubtreeSolution(rootId,desiredRoot)'),'blank-canvas drops must preserve manual placement and rigid independent subtrees');
assert.ok(main.includes('Router.routeIncident(temp,ids,this.routes||{})'),'ordinary connected movement must reroute only incident edges');
assert.ok(main.includes('applyPaneRatio()')&&main.includes('this.syncSelectionUi();')&&!main.includes('this.renderQueued'),'hot interactions must update styles/classes without a redundant render queue');
assert.ok(main.includes('MULTIPARENT_PARENT_CONFLICT'),'relation drop must show the amended clause 83 conflict');
assert.ok(main.includes("Router.routeAll(this.canvas,[],this.routes)"),'rendering must preserve existing legal routes');
assert.ok(main.includes('cancelTemporary()'),'toolbar full-close path must cancel live pointer/resize gestures');
assert.ok(main.includes('color:e.color'),'anchor highlights must receive the entity actual color');
assert.ok(main.includes("marker.setAttribute('refX','10')"),'arrow tip must terminate at the child border endpoint');
assert.ok(css.includes('node-drop-active')&&css.includes('cgn-section-badge'),'memo transfer and grouped-item state need explicit visual feedback');
const graph=fs.readFileSync(path.join(root,'src/shared/graph.js'),'utf8'),router=fs.readFileSync(path.join(root,'src/content/router.js'),'utf8');
assert.ok(graph.includes('parentHierarchyConflictAfterAdd')&&graph.includes('parentSetsIndependent'),'clause 83 must be enforced before relation creation');
assert.ok(router.includes('tryPreferred')&&router.includes('simpleCandidates')&&!router.includes('layeredRoutes'),'router must preserve legal paths and use low-bend shared-trunk candidates');
assert.ok(router.includes('R.routeHierarchy=')&&router.includes('path.length>4'),'hierarchy routing must reject long fallback paths');
const chat=fs.readFileSync(path.join(root,'src/content/chatgpt.js'),'utf8');
assert.ok(chat.includes("removeEventListener('popstate',check)")&&chat.includes("removeEventListener('hashchange',check)"),'full close must remove navigation listeners');
assert.ok(chat.includes('IGNORED_MESSAGE_TEXT'),'message anchors must exclude page controls');
assert.ok(chat.includes('buildMessageIndex'),'anchor refresh must batch message DOM indexing');
const browserTest=fs.readFileSync(path.join(root,'tests/browser_integration.py'),'utf8');
assert.ok(browserTest.includes('CHATGPT_NET_CHROMIUM'),'browser integration must allow an explicit browser override');
assert.ok(!browserTest.includes("executable_path='/usr/bin/chromium'"),'browser integration must not hard-code a Linux-only executable');
assert.ok(browserTest.includes('stableRender20Ms')&&browserTest.includes('node-drop-active')&&browserTest.includes('scroll_after'),'browser integration must cover render stability, memo feedback and page-scroll isolation');
assert.ok(browserTest.includes('complex_hierarchy')&&browserTest.includes("'short':True")&&browserTest.includes("'notesStable':True"),'browser integration must cover obstructed multi-parent hierarchy routing');
const firefoxTest=fs.readFileSync(path.join(root,'tests','firefox_extension_integration.mjs'),'utf8');assert.ok(firefoxTest.includes('moz/addon/install')&&firefoxTest.includes('project-a')&&firefoxTest.includes('idleCpuSeconds'),'Firefox acceptance must install the XPI and cover project paths and resources');
console.log('static_audit.js: PASS');
