(() => {
  const NS = globalThis.ChatGPTNET = globalThis.ChatGPTNET || {};
  NS.C = Object.freeze({
    PRODUCT: 'ChatGPT NET',
    BASELINE: '1.5',
    IMPORT_BASELINES: Object.freeze(['1.3','1.4','1.5']),
    SCHEMA_VERSION: 1,
    HIERARCHY_LAYOUT_VERSION: 1,
    STORAGE_PREFIX: 'chatgpt-net:v1:',
    CANVAS_PREFIX: 'chatgpt-net:v1:canvas:',
    GLOBAL_KEY: 'chatgpt-net:v1:global',
    WORLD_W: 2880,
    WORLD_H: 3600,
    INITIAL_VIEW_W: 360,
    INITIAL_VIEW_H: 900,
    MAX_VIEW_W: 720,
    MAX_VIEW_H: 900,
    DEFAULT_SIDEBAR_W: 420,
    MIN_SIDEBAR_W: 300,
    MAX_SIDEBAR_W: 780,
    MIN_CHAT_RESERVED_W: 480,
    DEFAULT_MEMO_RATIO: 0.25,
    MIN_MEMO_RATIO: 0.12,
    MAX_MEMO_RATIO: 0.55,
    DEFAULT_ZOOM: 0.75,
    MIN_ZOOM: 0.25,
    MAX_ZOOM: 3,
    NODE_W: 176,
    NODE_MIN_W: 110,
    NODE_MAX_W: 360,
    NODE_MIN_H: 52,
    NODE_GAP: 16,
    ROUTE_GRID: 12,
    ROUTE_CLEARANCE: 8,
    ROUTE_TRUNK: 60,
    HISTORY_LIMIT: 15,
    SLEEP_MS: 10 * 60 * 1000,
    AUTOPAN_MARGIN: 34,
    COLORS: ['#C9D5E6', '#C9D9C5', '#E7DBB9'],
    TOAST_MS: 2600,
    MESSAGES: Object.freeze({
      NO_ROUTE: '无法建立该层级：当前没有合理的无冲突布局。',
      SELF_RELATION: '无法建立：节点不能成为自己的父节点。',
      DUPLICATE_RELATION: '无法建立：该父子关系已经存在。',
      CYCLE_RELATION: '无法建立：该父子关系会形成循环。',
      BATCH_HAS_PARENT: '无法建立：批量关系中的节点必须全部没有父级关系。',
      MULTIPARENT_PARENT_CONFLICT: '无法建立：同一节点的多个上游节点之间不能存在上游/下游关系。',
      CANNOT_DELETE_SHARED: '无法删除',
      COLLAPSE_MULTIPARENT: '包含多父节点，无法折叠',
      CANVAS_FULL: '画布已满',
      CANNOT_PLACE: '无法放置：当前位置附近没有无冲突空间。',
      SAVE_CONFLICT: '检测到另一标签页已修改当前画布。请刷新该标签页后继续，避免覆盖数据。',
      SAVE_FAILED: '保存失败，当前操作已撤销。',
      ANCHOR_MESSAGE_ONLY: '只能可靠定位到整条消息。',
      ANCHOR_MISSING: '无法可靠定位原正文。'
    })
  });
})();
