(() => {
  const NS=globalThis.ChatGPTNET,{C,U,Schema,Graph,Geo,Hierarchy,Router,Store,StoreRuntime,Chat,UI}=NS;

  class App {
    constructor(){
      this.enabled=true;this.mounted=false;this.canvas=null;this.global=null;this.root=null;this.sidebar=null;this.canvasWrap=null;this.world=null;this.svg=null;this.memo=null;this.memoList=null;
      this.canvasSelection=new Set();this.memoSelection=new Set();this.selectionArea='canvas';this.undoStack=[];this.redoStack=[];this.routes={};this.continuous=false;this.sleeping=false;this.conflict=false;this.dataInvalid=false;
      this.drag=null;this.box=null;this.pan=null;this.resize=null;this.splitDrag=null;this.sidebarDrag=null;this.pendingBranch=null;this.lastActivity=Date.now();this.sleepTimer=null;this.flashId=null;
      this.selectionPopup=null;this.highlights=null;this.unsubs=[];this.messageWatchOff=null;this.runtimeActive=false;this.writeChain=Promise.resolve();
    }
    async init(){
      this.global=await Store.loadGlobal();
      const tab=await Store.tabState();this.enabled=tab.enabled!==false;
      this._onRuntimeMessage=msg=>{if(msg?.type==='TAB_ENABLED'){this.enabled=msg.enabled;return this.enabled?this.mountAndLoad():this.fullClose();}};browser.runtime.onMessage.addListener(this._onRuntimeMessage);
      this._onStorageChanged=(changes,area)=>{if(area==='local'&&changes[C.GLOBAL_KEY]?.newValue){const next=changes[C.GLOBAL_KEY].newValue;if(Schema.validateGlobal(next)){this.global=next;StoreRuntime.global=this.global;if(!this.canvas)UI.reservePage(next.sidebarWidth||C.DEFAULT_SIDEBAR_W,true);this.render();}}};
      if(this.enabled)await this.mountAndLoad();
    }
    activateRuntime(){
      if(this.runtimeActive)return;this.runtimeActive=true;browser.storage.onChanged.addListener(this._onStorageChanged);
      this.selectionPopup=UI.createSelectionPopup(parts=>this.createFromSelection(parts));this.highlights=UI.createHighlights(ids=>this.reverseLocate(ids));
      this.unsubs.push(Chat.watchNavigation(()=>this.onNavigation()));
      this.unsubs.push(Chat.watchBranchIntent(()=>this.captureBranchIntent()));
      this.unsubs.push(Chat.watchTitle(title=>{if(this.enabled&&this.mounted&&!this.sleeping&&this.canvas&&this.canvas.conversationId===Chat.conversationId()){this.canvas.title=title;this.titleEl.textContent=title;clearTimeout(this._titleSave);this._titleSave=setTimeout(()=>this.persistView(),250);}}));
      this.startMessageWatch();
      this._onScroll=e=>{if(!(e.target instanceof Element)||!e.target.closest('[data-chatgpt-net-root]'))this.renderHighlightsSoon();};this._onMouseUp=e=>this.onDocumentMouseUp(e);this._onKeyDown=e=>this.onKeyDown(e);
      this._onBlur=()=>{if(this.drag||this.resize||this.box||this.pan||this.splitDrag||this.sidebarDrag)this.cancelTemporary();};
      this._onResize=()=>{if(!this.mounted||this._resizeFrame)return;this._resizeFrame=requestAnimationFrame(()=>{this._resizeFrame=null;if(!this.mounted)return;UI.reservePage(this.canvas?.view.sidebarWidth||C.DEFAULT_SIDEBAR_W,true);this.clampPan(false);this.render();this.renderHighlightsSoon();});};
      document.addEventListener('scroll',this._onScroll,true);document.addEventListener('mouseup',this._onMouseUp,true);document.addEventListener('keydown',this._onKeyDown,true);window.addEventListener('blur',this._onBlur,true);window.addEventListener('resize',this._onResize,{passive:true});
    }
    startMessageWatch(){if(!this.runtimeActive||this.sleeping||this.messageWatchOff)return;this.messageWatchOff=Chat.watchMessages(()=>{this.ensurePageReserve();this.renderHighlightsSoon();});}
    stopMessageWatch(){if(!this.messageWatchOff)return;try{this.messageWatchOff();}catch{}this.messageWatchOff=null;}
    deactivateRuntime(){
      if(!this.runtimeActive)return;this.runtimeActive=false;try{browser.storage.onChanged.removeListener(this._onStorageChanged);}catch{}this.stopMessageWatch();for(const off of this.unsubs.splice(0))try{off();}catch{}
      document.removeEventListener('scroll',this._onScroll,true);document.removeEventListener('mouseup',this._onMouseUp,true);document.removeEventListener('keydown',this._onKeyDown,true);window.removeEventListener('blur',this._onBlur,true);window.removeEventListener('resize',this._onResize);
      this.selectionPopup?.destroy();this.highlights?.destroy();this.selectionPopup=null;this.highlights=null;clearTimeout(this._hlTimer);clearTimeout(this._anchorStatusSave);if(this._resizeFrame)cancelAnimationFrame(this._resizeFrame);this._resizeFrame=null;
    }
    async mountAndLoad(){
      this.activateRuntime();if(!this.mounted)this.mount();
      this.wake();
      await this.loadConversation(Chat.conversationId());
    }
    mount(){
      this.root=UI.el('div');this.root.dataset.chatgptNetRoot='';
      this.sidebar=UI.el('aside','cgn-sidebar');this.root.append(this.sidebar);document.body.append(this.root);this.mounted=true;
      this.sidebar.addEventListener('pointerdown',()=>this.activity(),true);this.sidebar.addEventListener('keydown',()=>this.activity(),true);
      this.buildShell();UI.reservePage(this.global?.sidebarWidth||C.DEFAULT_SIDEBAR_W,true);this.startSleepTimer();
    }
    async fullClose(){
      // Closing from browser chrome can happen in the middle of a page gesture/edit. Resolve those
      // transactions before tearing down DOM/listeners so no detached pointer listener or typed edit
      // is left behind. A failed final view save keeps its error toast visible after the sidebar closes.
      const active=document.activeElement;if(active instanceof HTMLElement&&active.closest?.('[data-chatgpt-net-root]'))active.blur();
      try{await this.writeChain;}catch{}
      if(this.drag||this.resize||this.box||this.pan||this.splitDrag||this.sidebarDrag)this.cancelTemporary();
      clearTimeout(this._zoomSave);clearTimeout(this._titleSave);clearTimeout(this._anchorStatusSave);
      if(this.canvas&&this.mounted&&!this.conflict)await this.persistView();
      this.sleeping=true;this.selectionPopup?.hide();this.highlights?.clear();this.stopSleepTimer();this.deactivateRuntime();
      document.querySelectorAll('.cgn-modal-backdrop,.cgn-ghost,.cgn-create-popup,.cgn-highlight').forEach(el=>el.remove());
      this.root?.remove();this.root=null;this.sidebar=null;this.mounted=false;this.canvasWrap=null;this.world=null;this.svg=null;this.memo=null;this.memoList=null;UI.reservePage(0,false);this.canvasSelection.clear();this.memoSelection.clear();this.drag=null;this.box=null;this.pan=null;this.resize=null;this.splitDrag=null;this.sidebarDrag=null;this.pendingBranch=null;
    }
    ensurePageReserve(){if(this.enabled&&this.mounted)UI.reservePage(this.canvas?.view.sidebarWidth||this.global?.sidebarWidth||C.DEFAULT_SIDEBAR_W,true);}
    buildShell(){
      this.sidebar.replaceChildren();
      const resize=UI.el('div','cgn-sidebar-resize');resize.addEventListener('pointerdown',e=>this.startSidebarResize(e));this.sidebar.append(resize);
      this.titleEl=UI.el('div','cgn-title','ChatGPT NET');this.sidebar.append(this.titleEl);
      this.toolbar=UI.el('div','cgn-toolbar');this.sidebar.append(this.toolbar);this.buildToolbar();
      this.main=UI.el('div','cgn-main');this.sidebar.append(this.main);
      this.canvasWrap=UI.el('div','cgn-canvas-wrap');this.main.append(this.canvasWrap);
      this.world=UI.el('div','cgn-world');this.canvasWrap.append(this.world);
      this.svg=document.createElementNS('http://www.w3.org/2000/svg','svg');this.svg.setAttribute('class','cgn-edges');this.world.append(this.svg);
      this.nodesLayer=UI.el('div','cgn-nodes');this.nodesLayer.style.cssText='position:absolute;inset:0;';this.world.append(this.nodesLayer);
      this.canvasWrap.addEventListener('pointerdown',e=>this.onCanvasPointerDown(e));
      this.canvasWrap.addEventListener('wheel',e=>this.onWheel(e),{passive:false});
      this.canvasWrap.addEventListener('dragover',e=>{if(e.dataTransfer?.types.includes('application/x-chatgpt-net-memo'))e.preventDefault();});
      this.canvasWrap.addEventListener('drop',e=>this.onMemoDropToCanvas(e));
      this.split=UI.el('div','cgn-split');this.split.addEventListener('pointerdown',e=>this.startSplit(e));this.main.append(this.split);
      this.memo=UI.el('section','cgn-memo');this.main.append(this.memo);
      const mh=UI.el('div','cgn-memo-head');mh.append(document.createTextNode('备忘录'));const plus=UI.el('button','plus','＋');plus.title='新建分隔标题';plus.onclick=()=>this.beginNewSection();mh.append(plus);this.memo.append(mh);
      this.memoList=UI.el('div','cgn-memo-list');this.memo.append(this.memoList);
      this.memoList.addEventListener('dragover',e=>{if(e.dataTransfer?.types.includes('application/x-chatgpt-net-memo'))e.preventDefault();});
      this.memoList.addEventListener('drop',e=>{if(e.target===this.memoList)this.dropMemoUngrouped(e);});
    }
    buildToolbar(){
      const add=(text,title,fn)=>{const b=UI.el('button','cgn-btn',text);b.title=title||text;b.onclick=fn;this.toolbar.append(b);return b;};
      this.btnUndo=add('撤回','撤回 Ctrl+Z',()=>this.undo());
      this.btnRedo=add('重做','重做 Ctrl+Shift+Z',()=>this.redo());
      this.btnContinuous=add('连续摘录','连续摘录',()=>{this.continuous=!this.continuous;this.selectionPopup?.hide();this.updateToolbar();});
      this.btnFree=add('自由节点','自由节点',()=>this.createFreeNode());
      this.btnDelete=add('删除','删除当前选择',()=>this.deleteSelected());
      this.btnUnlink=add('解除','删除所选节点全部父级关系',()=>this.unlinkSelected());
      this.btnSearch=add('搜索','搜索当前对话 ChatGPT NET 内容',()=>this.openSearch());
      this.colorButtons=[];for(let i=0;i<C.COLORS.length;i++){const b=UI.el('button','cgn-color');b.title=`颜色槽 ${i+1}`;b.onclick=()=>this.applyColorSlot(i);this.toolbar.append(b);this.colorButtons.push(b);}
      this.btnColorGear=add('⚙','修改当前颜色槽',()=>this.openColorSettings());
      this.btnZoom=add('75%','双击恢复 75% 并居中当前内容',()=>{});this.btnZoom.ondblclick=e=>{e.preventDefault();this.resetZoomAndCenter();};
      this.btnSettings=add('设置','导入、导出与备份',()=>this.openSettings());
      this.updateToolbar();
    }
    updateToolbar(){
      if(!this.toolbar)return;const has=!!this.canvas&&!this.conflict&&!this.dataInvalid;this.btnUndo.disabled=!has||!this.undoStack.length;this.btnRedo.disabled=!has||!this.redoStack.length;this.btnFree.disabled=!has;this.btnDelete.disabled=!has||(!this.canvasSelection.size&&!this.memoSelection.size);this.btnUnlink.disabled=!has||!this.canvasSelection.size;this.btnSearch.disabled=!this.canvas;
      this.btnContinuous.classList.toggle('active',this.continuous);this.btnContinuous.disabled=!has;
      const colors=this.canvas?StoreRuntime.colorsFor(this.canvas):this.global?.colorSlots||C.COLORS,slot=this.canvas?.view.activeColorSlot??0;
      this.colorButtons.forEach((b,i)=>{b.style.background=colors[i];b.classList.toggle('active',i===slot);b.disabled=!has;});
      this.btnColorGear.disabled=!has;this.btnZoom.textContent=`${Math.round((this.canvas?.view.zoom||C.DEFAULT_ZOOM)*100)}%`;
    }
    async loadConversation(conversationId){
      this.continuous=false;this.selectionPopup?.hide();this.canvasSelection.clear();this.memoSelection.clear();this.undoStack=[];this.redoStack=[];this.conflict=false;this.dataInvalid=false;
      if(!conversationId){this.canvas=null;this.titleEl.textContent='ChatGPT NET';this.render();return;}
      let c=await Store.loadCanvas(conversationId),isNew=false;
      if(c&&(!Schema.validateCanvas(c)||!Router.routeAll(c).ok)){this.canvas=null;this.dataInvalid=true;this.titleEl.textContent='ChatGPT NET · 数据需修复';this.render();UI.toast('当前 ChatGPT NET 数据无效，已停止写入并保留原数据。');return;}
      if(!c){c=Schema.newCanvas(conversationId,Chat.title());isNew=true;c.view.sidebarWidth=this.global.sidebarWidth||C.DEFAULT_SIDEBAR_W;c.view.memoRatio=this.global.memoRatio||C.DEFAULT_MEMO_RATIO;}
      c.view.activeColorSlot=U.clamp(Number(c.view.activeColorSlot)||0,0,C.COLORS.length-1);c.view.autoGroupIds=Array.isArray(c.view.autoGroupIds)?c.view.autoGroupIds:[];
      this.canvas=c;this.routes=Router.routeAll(c).routes;if(!isNew)c=await this.upgradeHierarchyLayout(c);this.canvas=c;this.sidebar.style.width=`${c.view.sidebarWidth}px`;UI.reservePage(c.view.sidebarWidth,true);this.titleEl.textContent=c.title||Chat.title();if(isNew){this.canvasWrap.style.flexBasis=`${(1-c.view.memoRatio)*100}%`;this.memo.style.flexBasis=`${c.view.memoRatio*100}%`;this.setInitialView(c);}this.clampPan(false);this.render();this.renderHighlightsSoon();
    }
    async onNavigation(){
      if(!this.enabled)return;const newId=Chat.conversationId(),old=this.canvas?.conversationId;this.continuous=false;this.selectionPopup?.hide();
      if(newId===old)return;
      clearTimeout(this._zoomSave);clearTimeout(this._titleSave);clearTimeout(this._anchorStatusSave);if(this.canvas&&!this.conflict&&!this.dataInvalid)await this.persistView();
      const pending=this.pendingBranch;this.pendingBranch=null;
      if(pending&&newId&&newId!==pending.sourceConversationId&&Date.now()-pending.at<15000){
        const verified=await Chat.waitForBranchFingerprint(pending.fingerprint,3200);
        if(verified&&this.enabled&&this.runtimeActive&&this.mounted&&Chat.conversationId()===newId){const existing=await Store.loadCanvas(newId);
          if(!existing){
            const clone=Graph.cloneForBranch(pending.source,newId,Chat.title(),Chat.reliablyLocatableEntityIds(pending.source));
            try{const r=await Store.saveCanvas(clone,0);this.canvas=r.canvas;this.undoStack=[];this.redoStack=[];this.canvasSelection.clear();this.memoSelection.clear();this.buildShell();this.render();this.renderHighlightsSoon();return;}catch(e){UI.toast('分支画布复制失败，已保留来源画布数据。');}
          }
        }
      }
      await this.loadConversation(newId);
    }
    captureBranchIntent(){if(this.canvas&&this.enabled){const source=U.deepClone(this.canvas);source.colorOverride=[...StoreRuntime.colorsFor(this.canvas)];this.pendingBranch={source,sourceConversationId:this.canvas.conversationId,fingerprint:Chat.conversationFingerprint(),at:Date.now()};}}
    activity(){this.lastActivity=Date.now();if(this.sleeping)this.wake();}
    startSleepTimer(){this.stopSleepTimer();this.sleepTimer=setInterval(()=>{if(!this.sleeping&&Date.now()-this.lastActivity>=C.SLEEP_MS)this.sleep();},30000);}
    stopSleepTimer(){if(this.sleepTimer)clearInterval(this.sleepTimer);this.sleepTimer=null;}
    sleep(){this.sleeping=true;this.stopMessageWatch();this.highlights?.clear();if(this.canvasWrap&&!this.canvasWrap.querySelector('.cgn-sleep')){const o=UI.el('div','cgn-sleep','画布已休眠 · 点击恢复');o.onclick=()=>this.wake();this.canvasWrap.append(o);}}
    wake(){this.sleeping=false;this.lastActivity=Date.now();this.startMessageWatch();this.canvasWrap?.querySelector('.cgn-sleep')?.remove();if(this.canvas){const t=Chat.title();if(t&&t!==this.canvas.title){this.canvas.title=t;if(this.titleEl)this.titleEl.textContent=t;clearTimeout(this._titleSave);this._titleSave=setTimeout(()=>this.persistView(),250);}}this.renderHighlightsSoon();}
    enqueue(fn){const p=this.writeChain.then(fn,fn);this.writeChain=p.catch(()=>{});return p;}
    historyTarget(target,current){
      const out=U.deepClone(target);out.title=current.title;out.colorOverride=U.deepClone(current.colorOverride);
      for(const k of['zoom','panX','panY','sidebarWidth','memoRatio','activeColorSlot','hierarchyLayoutVersion'])if(k in current.view)out.view[k]=current.view[k];
      for(const[id,p]of Object.entries(out.canvasPlacements))if(current.canvasPlacements[id])p.subtreeCollapsed=!!current.canvasPlacements[id].subtreeCollapsed;
      for(const[sid,sec]of Object.entries(out.memoSections))if(current.memoSections[sid])sec.collapsed=!!current.memoSections[sid].collapsed;
      for(const[id,e]of Object.entries(out.entities))if(current.entities[id])e.anchorStatus=current.entities[id].anchorStatus;
      for(const[id,p]of Object.entries(out.canvasPlacements))if(p.subtreeCollapsed&&!Graph.canCollapse(out,id))p.subtreeCollapsed=false;
      return out;
    }
    endAutoGroupIfTouched(c,ids){const active=new Set(c.view.autoGroupIds||[]);if(ids.some(id=>active.has(id)))c.view.autoGroupIds=[];}
    async mutate(mutator,opts={}){return this.enqueue(()=>this._mutate(mutator,opts));}
    async _mutate(mutator,{history=true,validateRoutes=true,toastOnRoute=false,preferredRoutes=this.routes}={}){
      if(!this.canvas||this.conflict)return false;const before=U.deepClone(this.canvas);let ok;
      try{ok=await mutator(this.canvas);if(ok===false){this.canvas=before;this.render();return false;}if(validateRoutes){const rr=Router.routeAll(this.canvas,[],preferredRoutes);if(!rr.ok){this.canvas=before;this.render();if(toastOnRoute)UI.toast(C.MESSAGES.NO_ROUTE);return false;}this.routes=rr.routes;}
        const expected=before.revision||0,r=await Store.saveCanvas(this.canvas,expected);this.canvas=r.canvas;if(history){this.undoStack.push(before);if(this.undoStack.length>C.HISTORY_LIMIT)this.undoStack.shift();this.redoStack=[];}this.render();this.renderHighlightsSoon();return true;
      }catch(e){this.canvas=before;if(e.code==='CONFLICT'){this.conflict=true;this.continuous=false;UI.toast(C.MESSAGES.SAVE_CONFLICT);}else{console.error('[ChatGPT NET] save failed',e);UI.toast(C.MESSAGES.SAVE_FAILED);}this.render();return false;}
    }
    async persistView(){return this.enqueue(()=>this._persistView());}
    async _persistView(){if(!this.canvas||this.conflict)return false;const before=this.canvas.revision||0;try{const r=await Store.saveCanvas(this.canvas,before);this.canvas=r.canvas;this.updateToolbar();return true;}catch(e){if(e.code==='CONFLICT'){this.conflict=true;this.continuous=false;UI.toast(C.MESSAGES.SAVE_CONFLICT);}else UI.toast(C.MESSAGES.SAVE_FAILED);this.updateToolbar();return false;}}
    async undo(){return this.enqueue(()=>this._undo());}
    async _undo(){if(!this.canvas||!this.undoStack.length||this.conflict)return;const raw=this.undoStack.pop(),current=U.deepClone(this.canvas),target=this.historyTarget(raw,current),rr=Router.routeAll(target);if(!rr.ok){this.undoStack.push(raw);UI.toast(C.MESSAGES.SAVE_FAILED);return;}try{const r=await Store.saveCanvas(target,current.revision||0);this.canvas=r.canvas;this.routes=rr.routes;this.redoStack.push(current);this.canvasSelection.clear();this.memoSelection.clear();this.render();this.renderHighlightsSoon();}catch(e){this.undoStack.push(raw);this.conflict=e.code==='CONFLICT';if(this.conflict)this.continuous=false;UI.toast(this.conflict?C.MESSAGES.SAVE_CONFLICT:C.MESSAGES.SAVE_FAILED);this.updateToolbar();}}
    async redo(){return this.enqueue(()=>this._redo());}
    async _redo(){if(!this.canvas||!this.redoStack.length||this.conflict)return;const raw=this.redoStack.pop(),current=U.deepClone(this.canvas),target=this.historyTarget(raw,current),rr=Router.routeAll(target);if(!rr.ok){this.redoStack.push(raw);UI.toast(C.MESSAGES.SAVE_FAILED);return;}try{const r=await Store.saveCanvas(target,current.revision||0);this.canvas=r.canvas;this.routes=rr.routes;this.undoStack.push(current);if(this.undoStack.length>C.HISTORY_LIMIT)this.undoStack.shift();this.canvasSelection.clear();this.memoSelection.clear();this.render();this.renderHighlightsSoon();}catch(e){this.redoStack.push(raw);this.conflict=e.code==='CONFLICT';if(this.conflict)this.continuous=false;UI.toast(this.conflict?C.MESSAGES.SAVE_CONFLICT:C.MESSAGES.SAVE_FAILED);this.updateToolbar();}}
    setInitialView(c){const z=c.view.zoom||C.DEFAULT_ZOOM,w=(this.canvasWrap?.clientWidth||C.INITIAL_VIEW_W)/z,h=(this.canvasWrap?.clientHeight||C.INITIAL_VIEW_H)/z;c.view.panX=U.clamp(C.WORLD_W*.5-w/2,0,Math.max(0,C.WORLD_W-w));c.view.panY=U.clamp(C.WORLD_H*.25-h/2,0,Math.max(0,C.WORLD_H-h));}
    viewportWorld(){if(!this.canvasWrap||!this.canvas)return{x:0,y:0,w:480,h:900};const z=this.canvas.view.zoom;return{x:this.canvas.view.panX,y:this.canvas.view.panY,w:this.canvasWrap.clientWidth/z,h:this.canvasWrap.clientHeight/z};}
    clientToWorld(clientX,clientY){const r=this.canvasWrap.getBoundingClientRect(),z=this.canvas.view.zoom;return{x:this.canvas.view.panX+(clientX-r.left)/z,y:this.canvas.view.panY+(clientY-r.top)/z};}
    applyTransform(){if(!this.canvas||!this.world)return;const {zoom,panX,panY}=this.canvas.view;this.world.style.transform=`translate(${-panX*zoom}px,${-panY*zoom}px) scale(${zoom})`;}
    applyPaneRatio(){if(!this.canvas)return;this.canvasWrap.style.flexBasis=`${(1-this.canvas.view.memoRatio)*100}%`;this.memo.style.flexBasis=`${this.canvas.view.memoRatio*100}%`;}
    clampPan(save=false){if(!this.canvas||!this.canvasWrap)return;const z=this.canvas.view.zoom,vw=(this.canvasWrap.clientWidth||C.INITIAL_VIEW_W)/z,vh=(this.canvasWrap.clientHeight||Math.min(C.INITIAL_VIEW_H,innerHeight))/z;this.canvas.view.panX=U.clamp(this.canvas.view.panX,0,Math.max(0,C.WORLD_W-vw));this.canvas.view.panY=U.clamp(this.canvas.view.panY,0,Math.max(0,C.WORLD_H-vh));this.applyTransform();if(save)this.persistView();}
    render(){
      if(!this.mounted||!this.sidebar)return;this.updateToolbar();const sidebarWidth=this.canvas?.view.sidebarWidth||this.global?.sidebarWidth||C.DEFAULT_SIDEBAR_W;this.sidebar.style.width=`${sidebarWidth}px`;
      if(!this.canvas){this.titleEl.textContent=this.dataInvalid?'ChatGPT NET · 数据需修复':'ChatGPT NET';this.nodesLayer?.replaceChildren();this.svg?.replaceChildren();this.memoList?.replaceChildren(UI.el('div','',this.dataInvalid?'当前画布数据无效，原数据已保留且写入已停止。':'请先打开一个 ChatGPT 对话。'));return;}
      this.titleEl.textContent=this.canvas.title||Chat.title();this.applyPaneRatio();this.applyTransform();
      this.renderNodesAndEdges();this.renderMemo();this.updateToolbar();
    }
    renderNodesAndEdges(){
      const hidden=Graph.hiddenByCollapse(this.canvas),existingNodes=new Map([...this.nodesLayer.querySelectorAll(':scope > .cgn-node[data-id]')].map(el=>[el.dataset.id,el]));
      for(const [id,p] of Object.entries(this.canvas.canvasPlacements)){
        if(hidden.has(id))continue;const ent=this.canvas.entities[id];if(!ent)continue;let n=existingNodes.get(id),text;if(!n){n=UI.el('div','cgn-node');n.dataset.id=id;text=UI.el('div','cgn-node-text');n.append(text);const l=UI.el('div','cgn-resize left'),r=UI.el('div','cgn-resize right');l.addEventListener('pointerdown',e=>this.startNodeResize(e,id,'left'));r.addEventListener('pointerdown',e=>this.startNodeResize(e,id,'right'));n.append(l,r);n.addEventListener('pointerdown',e=>this.startNodeDrag(e,id));n.addEventListener('dblclick',e=>{if(e.target.closest('.cgn-resize,.cgn-collapse-node'))return;e.stopPropagation();const el=n.querySelector('.cgn-node-text'),current=this.canvas.entities[id];if(el&&current)UI.inlineEdit(el,current.text,v=>this.editEntity(id,v));});this.nodesLayer.append(n);}else text=n.querySelector('.cgn-node-text');existingNodes.delete(id);
        n.className='cgn-node'+(ent.kind==='free'?' free':'')+(this.canvasSelection.has(id)?' selected':'')+(ent.anchorStatus==='missing'?' anchor-missing':'');n.style.left=`${p.x}px`;n.style.top=`${p.y}px`;n.style.width=`${p.width||C.NODE_W}px`;n.style.height=`${Math.max(C.NODE_MIN_H,p.height||C.NODE_MIN_H)}px`;n.style.background=ent.color;if(text&&!text.isContentEditable&&text.textContent!==ent.text)text.textContent=ent.text;
        n.querySelector('.cgn-collapse-node')?.remove();const children=Graph.childrenOf(this.canvas,id);if(children.length){const b=UI.el('button','cgn-collapse-node',p.subtreeCollapsed?'＋':'−'),can=Graph.canCollapse(this.canvas,id);if(!can)b.title=C.MESSAGES.COLLAPSE_MULTIPARENT;b.onclick=e=>{e.stopPropagation();if(can)this.toggleCollapse(id);};n.append(b);}
      }
      for(const n of existingNodes.values())n.remove();const edgeIds=Object.keys(this.canvas.relations);if(edgeIds.length!==Object.keys(this.routes||{}).length||edgeIds.some(id=>!this.routes[id])){const rr=Router.routeAll(this.canvas,[],this.routes);this.routes=rr.ok?rr.routes:{};}let defs=this.svg.querySelector('defs');if(!defs){defs=document.createElementNS('http://www.w3.org/2000/svg','defs');const marker=document.createElementNS('http://www.w3.org/2000/svg','marker'),arrow=document.createElementNS('http://www.w3.org/2000/svg','path');marker.setAttribute('id','cgn-arrow');marker.setAttribute('viewBox','0 0 10 10');marker.setAttribute('refX','10');marker.setAttribute('refY','5');marker.setAttribute('markerWidth','6');marker.setAttribute('markerHeight','6');marker.setAttribute('orient','auto-start-reverse');arrow.setAttribute('d','M 0 0 L 10 5 L 0 10 z');arrow.setAttribute('fill','#616873');marker.append(arrow);defs.append(marker);this.svg.append(defs);}
      const existing=new Map([...this.svg.querySelectorAll('.cgn-edge[data-edge-id]')].map(el=>[el.dataset.edgeId,el]));
      for(const [eid,path] of Object.entries(this.routes)){
        const edge=this.canvas.relations[eid];if(!edge||hidden.has(edge.parentId)||hidden.has(edge.childId))continue;let pl=existing.get(eid);if(!pl){pl=document.createElementNS('http://www.w3.org/2000/svg','polyline');pl.setAttribute('class','cgn-edge');pl.setAttribute('marker-end','url(#cgn-arrow)');pl.dataset.edgeId=eid;pl.addEventListener('dblclick',e=>this.onEdgeDoubleClick(e,eid));this.svg.append(pl);}const points=path.map(p=>`${p.x},${p.y}`).join(' ');if(pl.getAttribute('points')!==points)pl.setAttribute('points',points);existing.delete(eid);
      }for(const pl of existing.values())pl.remove();
    }
    renderMemo(){
      this.memoList.replaceChildren();const rendered=new Set();
      const renderItem=(id,container=this.memoList)=>{const ent=this.canvas.entities[id],mp=this.canvas.memoPlacements[id];if(!ent||!mp||rendered.has(id))return;rendered.add(id);const el=UI.el('div','cgn-memo-item'+(this.memoSelection.has(id)?' selected':'')+(ent.anchorStatus==='missing'?' anchor-missing':''),ent.text);el.dataset.id=id;el.style.background=ent.color;el.draggable=true;
        el.addEventListener('click',e=>this.onMemoClick(e,id));el.addEventListener('dblclick',e=>{e.preventDefault();UI.inlineEdit(el,ent.text,v=>this.editEntity(id,v));});el.addEventListener('dragstart',e=>this.onMemoDragStart(e,id));el.addEventListener('dragover',e=>{e.preventDefault();});el.addEventListener('drop',e=>this.dropMemoBefore(e,id));container.append(el);};
      for(const token of this.canvas.memoOrder||[]){
        if(token.startsWith('e:')){const id=token.slice(2);if(this.canvas.memoPlacements[id]?.sectionId==null)renderItem(id);}
        else if(token.startsWith('s:')){const sid=token.slice(2),sec=this.canvas.memoSections[sid];if(!sec)continue;const gap=UI.el('div','cgn-ungrouped-drop');gap.title='拖到此处成为未分组条目';gap.addEventListener('dragover',e=>{if(e.dataTransfer?.types.includes('application/x-chatgpt-net-memo'))e.preventDefault();});gap.addEventListener('drop',e=>this.dropMemoBeforeSection(e,sid));this.memoList.append(gap);const wrap=UI.el('div','cgn-section');wrap.dataset.sectionId=sid;const head=UI.el('div','cgn-section-head');head.draggable=true;const badge=UI.el('span','cgn-section-badge','分组'),label=UI.el('span','cgn-section-title',sec.title);head.append(badge,label);const count=(sec.itemIds||[]).length,toggle=UI.el('button','',sec.collapsed?`＋ ${count}`:'−'),del=UI.el('button','','×');toggle.title=sec.collapsed?`展开（${count}）`:'折叠';toggle.onclick=e=>{e.stopPropagation();this.toggleMemoSection(sid);};del.title='删除分隔标题（保留条目）';del.onclick=e=>{e.stopPropagation();this.deleteSection(sid);};head.append(toggle,del);head.addEventListener('dblclick',()=>UI.inlineEdit(label,sec.title,v=>this.renameSection(sid,v)));head.addEventListener('dragstart',e=>this.onSectionDragStart(e,sid));head.addEventListener('dragover',e=>e.preventDefault());head.addEventListener('drop',e=>{const ds=e.dataTransfer.getData('application/x-chatgpt-net-section');if(ds){e.preventDefault();e.stopPropagation();this.reorderSection(ds,sid);}else this.dropMemoToSection(e,sid);});wrap.append(head);if(!sec.collapsed){const body=UI.el('div','cgn-section-drop');body.addEventListener('dragover',e=>e.preventDefault());body.addEventListener('drop',e=>this.dropMemoToSection(e,sid));for(const id of sec.itemIds||[])renderItem(id,body);wrap.append(body);}this.memoList.append(wrap);}
      }
      for(const [id,mp] of Object.entries(this.canvas.memoPlacements))if(mp.sectionId==null&&!rendered.has(id))renderItem(id);
    }
    async editEntity(id,text){let preferred=this.routes;const temp=U.deepClone(this.canvas),ent=temp.entities[id],p=temp.canvasPlacements[id];if(!ent)return;if(p){ent.text=text;p.height=this.measureNodeHeight(text,p.width,ent.kind);const desired={[id]:{x:p.x,y:p.y}},connected=Graph.parentsOf(temp,id).length||Graph.childrenOf(temp,id).length;if(connected){const component=Hierarchy.component(temp,[id]),set=new Set(component);let found=null;for(const pos of Geo.nearestGroupCandidates(temp,[id],desired,32)){Object.assign(p,pos[id]);const down=Graph.edges(temp).filter(e=>set.has(e.parentId)&&set.has(e.childId)).every(e=>{const a=temp.canvasPlacements[e.parentId],b=temp.canvasPlacements[e.childId];return a.y+a.height<b.y;});if(!down)continue;const rr=Router.routeHierarchy(temp,component,this.routes);if(rr.ok){found={pos,rr};break;}}if(!found){UI.toast(C.MESSAGES.CANNOT_PLACE);this.render();return;}Object.assign(p,found.pos[id]);preferred=found.rr.routes;}else{const pos=Geo.findNearestGroup(temp,[id],desired);if(!pos){UI.toast(C.MESSAGES.CANNOT_PLACE);this.render();return;}Object.assign(p,pos[id]);}}const ok=await this.mutate(c=>{c.entities[id].text=text;c.entities[id].modifiedAt=U.now();if(p)Object.assign(c.canvasPlacements[id],p);return true;},{preferredRoutes:preferred});if(!ok)UI.toast(C.MESSAGES.CANNOT_PLACE);}
    async onDocumentMouseUp(e){
      if(!this.enabled||!this.mounted||!this.canvas||e.button!==0||this.drag||this.box||this.pan)return;if(!Chat.isMessageContentTarget(e.target)){this.selectionPopup?.hide();return;}
      await new Promise(r=>setTimeout(r,0));const parts=Chat.selectionParts();if(!parts.length){this.selectionPopup?.hide();return;}
      this.activity();const sel=getSelection(),rect=sel?.rangeCount?sel.getRangeAt(0).getBoundingClientRect():null;
      if(this.continuous){if(!e.ctrlKey&&!e.shiftKey)await this.createFromSelection(parts);this.selectionPopup?.hide();}
      else if(!e.ctrlKey&&!e.shiftKey&&rect)this.selectionPopup.show(parts,rect);else this.selectionPopup?.hide();
    }
    measureNodeHeight(text,width,kind='free'){const minimum=Schema.minimumNodeHeight(text,width);if(!this.nodesLayer)return minimum;const n=UI.el('div','cgn-node'+(kind==='free'?' free':''));n.style.cssText=`position:absolute;visibility:hidden;pointer-events:none;width:${width}px;height:auto;left:-9999px;top:-9999px`;n.textContent=text||'';this.nodesLayer.append(n);const h=Math.max(minimum,n.offsetHeight);n.remove();return h;}
    newNodeWidth(){const v=this.viewportWorld(),available=v.w-24;if(available<C.NODE_MIN_W)return null;return U.clamp(Math.min(C.NODE_W,available),C.NODE_MIN_W,C.NODE_MAX_W);}
    async createFromSelection(parts){if(!this.canvas||!parts.length)return;const created=[],width=this.newNodeWidth();if(!width){UI.toast(C.MESSAGES.CANVAS_FULL);return;}await this.mutate(c=>{for(const part of parts){const color=StoreRuntime.colorsFor(c)[c.view.activeColorSlot],ent=Schema.newEntity({kind:'anchor',text:part.text,originalText:part.originalText,anchor:part.anchor,color});c.entities[ent.entityId]=ent;c.canvasPlacements[ent.entityId]={entityId:ent.entityId,x:0,y:0,width,height:this.measureNodeHeight(part.text,width,'anchor'),subtreeCollapsed:false};created.push(ent.entityId);}return this.placeAutoGroup(c,created);},{toastOnRoute:false}).then(ok=>{if(!ok&&created.length)UI.toast(C.MESSAGES.CANVAS_FULL);});}
    async createFreeNode(){if(!this.canvas)return;const width=this.newNodeWidth();if(!width){UI.toast(C.MESSAGES.CANVAS_FULL);return;}let id=null;const ok=await this.mutate(c=>{const color=StoreRuntime.colorsFor(c)[c.view.activeColorSlot],ent=Schema.newEntity({kind:'free',text:'自由节点',color});id=ent.entityId;c.entities[id]=ent;c.canvasPlacements[id]={entityId:id,x:0,y:0,width,height:this.measureNodeHeight('自由节点',width,'free'),subtreeCollapsed:false};return this.placeAutoGroup(c,[id]);});if(!ok){UI.toast(C.MESSAGES.CANVAS_FULL);return;}this.canvasSelection=new Set([id]);this.memoSelection.clear();this.syncSelectionUi();setTimeout(()=>{const el=this.nodesLayer.querySelector(`[data-id="${CSS.escape(id)}"] .cgn-node-text`);if(el)UI.inlineEdit(el,this.canvas.entities[id].text,v=>this.editEntity(id,v));});}
    placeAutoGroup(c,newIds){
      const old=(c.view.autoGroupIds||[]).filter(id=>c.canvasPlacements[id]&&c.entities[id]&&!Graph.parentsOf(c,id).length&&!Graph.childrenOf(c,id).length),ids=[...old,...newIds],view=this.viewportWorld(),gap=C.NODE_GAP,available=Math.max(0,view.w-24),rows=[];let row=[],rowW=0;
      for(const id of ids){const p=c.canvasPlacements[id],w=p.width||C.NODE_W;if(w>available)return false;const next=row.length?rowW+gap+w:w;if(row.length&&next>available){rows.push(row);row=[id];rowW=w;}else{row.push(id);rowW=next;}}if(row.length)rows.push(row);
      const rowMeta=rows.map(r=>({ids:r,w:r.reduce((a,id)=>a+(c.canvasPlacements[id].width||C.NODE_W),0)+gap*(r.length-1),h:Math.max(...r.map(id=>c.canvasPlacements[id].height||C.NODE_MIN_H))})),totalH=rowMeta.reduce((a,r)=>a+r.h,0)+gap*(rowMeta.length-1);if(totalH>view.h-24)return false;
      let y=view.y+view.h*.58;if(y+totalH>view.y+view.h-12)y=view.y+view.h-totalH-12;if(y<view.y+12)y=view.y+12;const positions={};for(const rm of rowMeta){let x=view.x+view.w/2-rm.w/2;for(const id of rm.ids){positions[id]={x,y};x+=(c.canvasPlacements[id].width||C.NODE_W)+gap;}y+=rm.h+gap;}
      const group=new Set(ids),visibleLegal=()=>{for(const id of ids){const p=c.canvasPlacements[id],pos=positions[id],r={x:pos.x,y:pos.y,w:p.width,h:p.height};if(r.x<view.x||r.y<view.y||r.x+r.w>view.x+view.w||r.y+r.h>view.y+view.h||!Geo.inWorld(r))return false;for(const[oid,op]of Object.entries(c.canvasPlacements)){if(group.has(oid))continue;if(U.rectsOverlap(r,Geo.nodeRect(op),C.NODE_GAP))return false;}}return true;};
      const applyGroup=()=>{for(const id of ids){c.canvasPlacements[id].x=positions[id].x;c.canvasPlacements[id].y=positions[id].y;}};
      const existing=()=>Object.entries(c.canvasPlacements).filter(([id])=>!group.has(id));
      for(let attempt=0;attempt<80;attempt++){if(visibleLegal()){applyGroup();if(Router.routeAll(c).ok){c.view.autoGroupIds=ids;return true;}}const others=existing();if(!others.length)break;const dy=Math.min(48,...others.map(([,p])=>p.y));if(!(dy>0))break;for(const[,p]of others)p.y-=dy;}
      return false;
    }
    selectCanvas(id,ctrl=false){this.memoSelection.clear();this.selectionArea='canvas';if(ctrl){this.canvasSelection.has(id)?this.canvasSelection.delete(id):this.canvasSelection.add(id);}else if(!this.canvasSelection.has(id)||this.canvasSelection.size!==1){this.canvasSelection.clear();this.canvasSelection.add(id);}this.syncSelectionUi();}
    syncSelectionUi(){this.nodesLayer?.querySelectorAll('.cgn-node').forEach(el=>el.classList.toggle('selected',this.canvasSelection.has(el.dataset.id)));this.memoList?.querySelectorAll('.cgn-memo-item[data-id]').forEach(el=>el.classList.toggle('selected',this.memoSelection.has(el.dataset.id)));this.updateToolbar();}
    syncAnchorStatusUi(){for(const root of [this.nodesLayer,this.memoList])root?.querySelectorAll('[data-id]').forEach(el=>el.classList.toggle('anchor-missing',this.canvas?.entities[el.dataset.id]?.anchorStatus==='missing'));}
    startNodeDrag(e,id){
      if(!U.isPrimary(e)||e.target.closest('.cgn-resize,.cgn-collapse-node')||e.target.isContentEditable)return;e.preventDefault();e.stopPropagation();this.activity();
      if(e.shiftKey){this.memoSelection.clear();this.selectionArea='canvas';this.jumpToAnchor(id);return;}
      this.memoSelection.clear();this.selectionArea='canvas';
      let collapseOnClick=false;
      if(e.ctrlKey){if(this.canvasSelection.has(id)){this.canvasSelection.delete(id);this.syncSelectionUi();return;}this.canvasSelection.add(id);}else if(!this.canvasSelection.has(id)){this.canvasSelection.clear();this.canvasSelection.add(id);}else if(this.canvasSelection.size>1){collapseOnClick=true;}
      this.syncSelectionUi();
      const ids=[...this.canvasSelection];if(!ids.length)return;const start=this.clientToWorld(e.clientX,e.clientY),orig={};ids.forEach(x=>{const p=this.canvas.canvasPlacements[x];orig[x]={x:p.x,y:p.y};});this.drag={kind:'nodes',pointerId:e.pointerId,ids,start,clientStart:{x:e.clientX,y:e.clientY},orig,clickId:id,collapseOnClick,dx:0,dy:0,moved:false,viewOrig:{panX:this.canvas.view.panX,panY:this.canvas.view.panY},ghost:null};
      try{e.currentTarget.setPointerCapture?.(e.pointerId);}catch{}
      const cleanup=()=>{window.removeEventListener('pointermove',move,true);window.removeEventListener('pointerup',up,true);window.removeEventListener('pointercancel',cancel,true);},move=ev=>this.moveNodeDrag(ev),up=ev=>{cleanup();this.finishNodeDrag(ev);},cancel=()=>{cleanup();this.cancelDrag();};this.drag.cleanup=cleanup;window.addEventListener('pointermove',move,true);window.addEventListener('pointerup',up,true);window.addEventListener('pointercancel',cancel,true);
    }
    memoDropHit(x,y){const sr=this.sidebar?.getBoundingClientRect(),split=this.split?.getBoundingClientRect();return!!sr&&!!split&&x>=sr.left&&x<=sr.right&&y>=split.top-18&&y<=sr.bottom;}
    moveNodeDrag(e){if(!this.drag||this.drag.kind!=='nodes')return;e.preventDefault();e.stopPropagation();const p=this.clientToWorld(e.clientX,e.clientY),dx=p.x-this.drag.start.x,dy=p.y-this.drag.start.y;this.drag.dx=dx;this.drag.dy=dy;const distance=Math.hypot(e.clientX-this.drag.clientStart.x,e.clientY-this.drag.clientStart.y);if(!this.drag.moved&&distance<=7)return;if(!this.drag.moved)this.drag.moved=true;const overMemo=this.memoDropHit(e.clientX,e.clientY);this.memo?.classList.toggle('node-drop-active',overMemo);if(overMemo&&!this.drag.ghost){const ghost=UI.el('div','cgn-ghost',this.drag.ids.length>1?`${this.drag.ids.length} 个画布节点`:(this.canvas.entities[this.drag.ids[0]]?.text||'节点'));ghost.dataset.cgnNodeGhost='';document.body.append(ghost);this.drag.ghost=ghost;}else if(!overMemo&&this.drag.ghost){this.drag.ghost.remove();this.drag.ghost=null;}if(this.drag.ghost){this.drag.ghost.style.left=`${e.clientX+12}px`;this.drag.ghost.style.top=`${e.clientY+12}px`;}for(const id of this.drag.ids){const el=this.nodesLayer.querySelector(`[data-id="${CSS.escape(id)}"]`);if(el){el.style.left=`${this.drag.orig[id].x+dx}px`;el.style.top=`${this.drag.orig[id].y+dy}px`;el.classList.add('dragging');}}if(!overMemo)this.autoPan(e.clientX,e.clientY);}
    autoPan(x,y){const r=this.canvasWrap.getBoundingClientRect(),m=C.AUTOPAN_MARGIN,z=this.canvas.view.zoom;let dx=0,dy=0;if(x<r.left+m)dx=-18/z;else if(x>r.right-m)dx=18/z;if(y<r.top+m)dy=-18/z;else if(y>r.bottom-m)dy=18/z;if(dx||dy){this.canvas.view.panX+=dx;this.canvas.view.panY+=dy;this.clampPan(false);}}
    cancelDrag(restoreView=true){if(restoreView&&this.drag?.viewOrig&&this.canvas){this.canvas.view.panX=this.drag.viewOrig.panX;this.canvas.view.panY=this.drag.viewOrig.panY;}this.drag?.cleanup?.();this.drag?.ghost?.remove();this.memo?.classList.remove('node-drop-active');document.querySelectorAll('.cgn-ghost[data-cgn-node-ghost]').forEach(el=>el.remove());this.drag=null;this.render();}
    cancelTemporary(){
      if(this.drag)this.cancelDrag(true);
      if(this.pan&&this.canvas){this.canvas.view.panX=this.pan.panX;this.canvas.view.panY=this.pan.panY;}this.pan?.cleanup?.();this.pan=null;
      this.resize?.cleanup?.();this.resize=null;this.box?.cleanup?.();this.box?.el?.remove();this.box=null;
      if(this.splitDrag&&this.canvas){this.canvas.view.memoRatio=this.splitDrag.ratio;this.applyPaneRatio();}this.splitDrag?.cleanup?.();this.splitDrag=null;
      if(this.sidebarDrag&&this.canvas){this.canvas.view.sidebarWidth=this.sidebarDrag.width;this.canvas.view.panX=this.sidebarDrag.panX;this.canvas.view.panY=this.sidebarDrag.panY;if(this.sidebar)this.sidebar.style.width=`${this.sidebarDrag.width}px`;UI.reservePage(this.sidebarDrag.width,true);}this.sidebarDrag?.cleanup?.();this.sidebarDrag=null;
      this.render();
    }
    async finishNodeDrag(e){e.preventDefault();e.stopPropagation();const d=this.drag;d?.ghost?.remove();this.memo?.classList.remove('node-drop-active');document.querySelectorAll('.cgn-ghost[data-cgn-node-ghost]').forEach(el=>el.remove());this.drag=null;if(!d?.moved){if(d?.collapseOnClick&&d.clickId){this.canvasSelection.clear();this.canvasSelection.add(d.clickId);}this.syncSelectionUi();return;}if(this.memoDropHit(e.clientX,e.clientY)){await this.toMemo(d.ids);return;}
      const wp=this.clientToWorld(e.clientX,e.clientY),hidden=Graph.hiddenByCollapse(this.canvas),target=Object.entries(this.canvas.canvasPlacements).find(([id,p])=>!d.ids.includes(id)&&!hidden.has(id)&&U.pointInRect(wp,Geo.nodeRect(p)))?.[0];if(target){await this.finishRelationDrop(d,target);return;}await this.finishMoveDrop(d);
    }
    desiredFromDrag(d){const out={};for(const id of d.ids)out[id]={x:d.orig[id].x+d.dx,y:d.orig[id].y+d.dy};return out;}
    findRouteLegalPositions(temp,ids,desired){
      const old={};ids.forEach(id=>old[id]={x:temp.canvasPlacements[id].x,y:temp.canvasPlacements[id].y});const isolated=ids.every(id=>!Graph.parentsOf(temp,id).length&&!Graph.childrenOf(temp,id).length);for(const pos of Geo.nearestGroupCandidates(temp,ids,desired)){for(const id of ids)Object.assign(temp.canvasPlacements[id],pos[id]);if(isolated?Router.routesClearOfNodes(temp,ids,this.routes):Router.routeAll(temp,[],this.routes).ok)return pos;}ids.forEach(id=>Object.assign(temp.canvasPlacements[id],old[id]));return null;
    }
    findPlacementSolution(temp,ids,desired){
      const direct=this.findRouteLegalPositions(temp,ids,desired);if(direct)return{positions:direct,related:{}};
      const moving=new Set(ids),related=[...new Set(ids.flatMap(id=>[...Graph.parentsOf(temp,id),...Graph.childrenOf(temp,id)]).filter(id=>!moving.has(id)))].slice(0,3),offsets=[[0,-56],[0,56],[-56,0],[56,0]];
      for(const rid of related){const base=temp.canvasPlacements[rid];if(!base)continue;for(const[dx,dy]of offsets){const trial=U.deepClone(temp),rp=trial.canvasPlacements[rid],rect={x:base.x+dx,y:base.y+dy,w:rp.width,h:rp.height};if(!Geo.placementLegal(trial,rid,rect,moving))continue;rp.x=rect.x;rp.y=rect.y;const pos=Geo.findNearestGroup(trial,ids,desired);if(!pos)continue;for(const id of ids){trial.canvasPlacements[id].x=pos[id].x;trial.canvasPlacements[id].y=pos[id].y;}if(Router.routeAll(trial).ok)return{positions:pos,related:{[rid]:{x:rp.x,y:rp.y}}};}}
      return null;
    }
    hierarchyPlacementSolution(temp,seeds,baseRoutes=this.routes,options={}){
      const layout=Hierarchy.arrange(temp,seeds,options);if(!layout)return null;const original=Object.fromEntries(layout.ids.map(id=>[id,{x:temp.canvasPlacements[id].x,y:temp.canvasPlacements[id].y}])),set=new Set(layout.ids),preferred={};for(const[eid,path]of Object.entries(baseRoutes||{})){const e=temp.relations[eid];if(e&&!set.has(e.parentId)&&!set.has(e.childId))preferred[eid]=path;}
      const probe=U.deepClone(temp);for(const id of Object.keys(probe.canvasPlacements))if(!set.has(id))delete probe.canvasPlacements[id];for(const[eid,e]of Object.entries(probe.relations))if(!set.has(e.parentId)||!set.has(e.childId))delete probe.relations[eid];for(const id of layout.ids)Object.assign(probe.canvasPlacements[id],layout.positions[id]);if(!Router.routeHierarchy(probe,layout.ids).ok)return null;
      for(const[dx,dy]of Hierarchy.translationCandidates(temp,layout)){const positions={};for(const id of layout.ids)positions[id]={x:layout.positions[id].x+dx,y:layout.positions[id].y+dy};if(!Geo.groupLegal(temp,layout.ids,positions))continue;for(const id of layout.ids){temp.canvasPlacements[id].x=positions[id].x;temp.canvasPlacements[id].y=positions[id].y;}const routed=Router.routeHierarchy(temp,layout.ids,preferred);if(routed.ok)return{...layout,positions,preferredRoutes:preferred,routes:routed.routes};}
      for(const id of layout.ids)Object.assign(temp.canvasPlacements[id],original[id]);return null;
    }
    hierarchyComponents(canvas,seeds=null){
      const candidates=seeds||Graph.edges(canvas).flatMap(e=>[e.parentId,e.childId]),seen=new Set(),out=[];for(const id of candidates){if(seen.has(id)||!canvas.canvasPlacements[id]||(!Graph.parentsOf(canvas,id).length&&!Graph.childrenOf(canvas,id).length))continue;const ids=Hierarchy.component(canvas,[id]);ids.forEach(x=>seen.add(x));if(ids.length>1)out.push(ids);}return out;
    }
    async upgradeHierarchyLayout(canvas){
      if((canvas.view.hierarchyLayoutVersion||0)>=C.HIERARCHY_LAYOUT_VERSION)return canvas;const components=this.hierarchyComponents(canvas);if(!components.length){canvas.view.hierarchyLayoutVersion=C.HIERARCHY_LAYOUT_VERSION;return canvas;}
      const original=canvas,working=U.deepClone(canvas);let routes=Router.routeAll(working).routes;for(const ids of components){const solution=this.hierarchyPlacementSolution(working,[ids[0]],routes);if(solution)routes=solution.routes;}
      working.view.hierarchyLayoutVersion=C.HIERARCHY_LAYOUT_VERSION;try{const saved=await Store.saveCanvas(working,original.revision||0);this.routes=routes;return saved.canvas;}catch(e){console.warn('[ChatGPT NET] hierarchy layout upgrade deferred',e);this.routes=Router.routeAll(original).routes;return original;}
    }
    translatedSubtreeSolution(rootId,desiredRoot){
      const ids=Graph.independentSubtree(this.canvas,rootId);if(!ids)return null;const root=this.canvas.canvasPlacements[rootId],desired={};for(const id of ids){const p=this.canvas.canvasPlacements[id];desired[id]={x:p.x+desiredRoot.x-root.x,y:p.y+desiredRoot.y-root.y};}
      for(const positions of Geo.nearestGroupCandidates(this.canvas,ids,desired)){const dx=positions[rootId].x-root.x,dy=positions[rootId].y-root.y,temp=U.deepClone(this.canvas),routes={...this.routes},internal=[];let valid=true;for(const id of ids)Object.assign(temp.canvasPlacements[id],positions[id]);for(const[eid,e]of Object.entries(temp.relations))if(ids.includes(e.parentId)&&ids.includes(e.childId)){const path=this.routes[eid];if(!path){valid=false;break;}internal.push(eid);routes[eid]=path.map(p=>({x:p.x+dx,y:p.y+dy}));}if(!valid)continue;const routed=Router.routeHierarchy(temp,ids,routes),same=(a,b)=>a?.length===b?.length&&a.every((p,i)=>p.x===b[i].x&&p.y===b[i].y);if(routed.ok&&internal.every(eid=>same(routed.routes[eid],routes[eid])))return{positions,related:{},preferredRoutes:routed.routes};}
      return null;
    }
    manualConnectedMoveSolution(ids,desired){
      const temp=U.deepClone(this.canvas);for(const positions of Geo.nearestGroupCandidates(temp,ids,desired)){for(const id of ids)Object.assign(temp.canvasPlacements[id],positions[id]);const component=[...new Set(ids.flatMap(id=>Hierarchy.component(temp,[id])))];if(!Hierarchy.topDown(temp,component))continue;const routed=Router.routeIncident(temp,ids,this.routes||{});if(routed.ok)return{positions,related:{},preferredRoutes:routed.routes};}return null;
    }
    async finishMoveDrop(d){
      const before=U.deepClone(this.canvas),desired=this.desiredFromDrag(d),connected=d.ids.some(id=>Graph.parentsOf(this.canvas,id).length||Graph.childrenOf(this.canvas,id).length),subtree=d.ids.length===1?Graph.independentSubtree(this.canvas,d.ids[0]):null,temp=U.deepClone(this.canvas),solution=subtree?this.translatedSubtreeSolution(d.ids[0],desired[d.ids[0]]):connected?this.manualConnectedMoveSolution(d.ids,desired):this.findPlacementSolution(temp,d.ids,desired);if(!solution){this.canvas=before;this.render();UI.toast(C.MESSAGES.CANNOT_PLACE);return;}
      await this.mutate(c=>{for(const[id,p]of Object.entries(solution.positions)){if(c.canvasPlacements[id]){c.canvasPlacements[id].x=p.x;c.canvasPlacements[id].y=p.y;}}for(const[id,p]of Object.entries(solution.related))if(c.canvasPlacements[id]){c.canvasPlacements[id].x=p.x;c.canvasPlacements[id].y=p.y;}this.endAutoGroupIfTouched(c,d.ids);return true;},{toastOnRoute:false,preferredRoutes:solution.preferredRoutes||this.routes});
    }
    async finishRelationDrop(d,parentId){
      const ids=d.ids;if(ids.length>1&&ids.some(id=>Graph.parentsOf(this.canvas,id).length)){this.render();UI.toast(C.MESSAGES.BATCH_HAS_PARENT);return;}
      if(ids.some(id=>id===parentId)){this.render();UI.toast(C.MESSAGES.SELF_RELATION);return;}if(ids.some(id=>Graph.hasEdge(this.canvas,parentId,id))){this.render();UI.toast(C.MESSAGES.DUPLICATE_RELATION);return;}if(ids.some(id=>Graph.wouldCycle(this.canvas,parentId,id))){this.render();UI.toast(C.MESSAGES.CYCLE_RELATION);return;}if(ids.some(id=>Graph.parentHierarchyConflictAfterAdd(this.canvas,parentId,id))){this.render();UI.toast(C.MESSAGES.MULTIPARENT_PARENT_CONFLICT);return;}
      const temp=U.deepClone(this.canvas),desired=this.desiredFromDrag(d),referenceIds=Hierarchy.component(this.canvas,[parentId]),selectionIndex=new Map(ids.map((id,index)=>[id,index]));for(const id of ids)Object.assign(temp.canvasPlacements[id],desired[id]);ids.forEach(id=>Graph.addEdge(temp,parentId,id));const stable=[...new Set([...Graph.childrenOf(temp,parentId),...ids])].sort((a,b)=>temp.canvasPlacements[a].x-temp.canvasPlacements[b].x||(selectionIndex.get(a)??Infinity)-(selectionIndex.get(b)??Infinity)||(temp.entities[a]?.createdAt||0)-(temp.entities[b]?.createdAt||0)||a.localeCompare(b)),orderIndex=Object.fromEntries(stable.map((id,index)=>[id,index])),solution=this.hierarchyPlacementSolution(temp,[parentId,...ids],this.routes,{referenceIds,orderIndex});if(!solution){this.render();UI.toast(C.MESSAGES.NO_ROUTE);return;}
      const ok=await this.mutate(c=>{ids.forEach(id=>Graph.addEdge(c,parentId,id));for(const id of solution.ids){c.canvasPlacements[id].x=solution.positions[id].x;c.canvasPlacements[id].y=solution.positions[id].y;}c.view.hierarchyLayoutVersion=C.HIERARCHY_LAYOUT_VERSION;this.endAutoGroupIfTouched(c,[...solution.ids,parentId]);return true;},{toastOnRoute:true,preferredRoutes:solution.preferredRoutes});if(!ok)this.render();
    }
    startNodeResize(e,id,side){
      if(!U.isPrimary(e))return;e.preventDefault();e.stopPropagation();const p=this.canvas.canvasPlacements[id],start=this.clientToWorld(e.clientX,e.clientY),orig={x:p.x,width:p.width};const cleanup=()=>{window.removeEventListener('pointermove',move,true);window.removeEventListener('pointerup',up,true);window.removeEventListener('pointercancel',cancel,true);},move=ev=>{if(!this.resize)return;const w=this.clientToWorld(ev.clientX,ev.clientY),dx=w.x-start.x;let width=orig.width+(side==='right'?dx:-dx),x=orig.x+(side==='left'?dx:0);width=U.clamp(width,C.NODE_MIN_W,C.NODE_MAX_W);if(side==='left')x=orig.x+(orig.width-width);const el=this.nodesLayer.querySelector(`[data-id="${CSS.escape(id)}"]`);if(el){el.style.width=`${width}px`;el.style.left=`${x}px`;}this.resize.preview={x,width};},up=async()=>{cleanup();const r=this.resize;this.resize=null;if(!r?.preview){this.render();return;}const temp=U.deepClone(this.canvas),tp=temp.canvasPlacements[id];tp.x=r.preview.x;tp.width=r.preview.width;tp.height=this.measureNodeHeight(temp.entities[id].text,tp.width,temp.entities[id].kind);const connected=Graph.parentsOf(temp,id).length||Graph.childrenOf(temp,id).length,rr=connected?Router.routeHierarchy(temp,Hierarchy.component(temp,[id]),this.routes):Router.routeAll(temp,[],this.routes);if(!Geo.placementLegal(temp,id,Geo.nodeRect(tp))||!rr.ok){this.render();UI.toast(C.MESSAGES.CANNOT_PLACE);return;}await this.mutate(c=>{Object.assign(c.canvasPlacements[id],tp);this.endAutoGroupIfTouched(c,[id]);return true;},{preferredRoutes:rr.routes});},cancel=()=>{cleanup();this.resize=null;this.render();};this.resize={id,side,startX:start.x,orig,cleanup};window.addEventListener('pointermove',move,true);window.addEventListener('pointerup',up,true);window.addEventListener('pointercancel',cancel,true);
    }
    estimateHeight(text,width){const chars=Math.max(12,Math.floor((width-22)/7.2)),lines=Math.max(1,Math.ceil((text||'').length/chars));return Math.max(C.NODE_MIN_H,20+lines*18);}
    onCanvasPointerDown(e){
      if(!this.canvas||!U.isPrimary(e)||e.target.closest('.cgn-node,.cgn-edge'))return;e.preventDefault();e.stopPropagation();this.activity();const r=this.canvasWrap.getBoundingClientRect();if(e.ctrlKey){this.memoSelection.clear();this.selectionArea='canvas';const start={x:e.clientX-r.left,y:e.clientY-r.top};this.box={start,current:start};const box=UI.el('div','cgn-selection-box');this.canvasWrap.append(box);this.box.el=box;const cleanup=()=>{window.removeEventListener('pointermove',move,true);window.removeEventListener('pointerup',up,true);window.removeEventListener('pointercancel',cancel,true);},move=ev=>{if(!this.box)return;ev.preventDefault();ev.stopPropagation();this.box.current={x:ev.clientX-r.left,y:ev.clientY-r.top};const x=Math.min(start.x,this.box.current.x),y=Math.min(start.y,this.box.current.y),w=Math.abs(this.box.current.x-start.x),h=Math.abs(this.box.current.y-start.y);Object.assign(box.style,{left:`${x}px`,top:`${y}px`,width:`${w}px`,height:`${h}px`});},up=()=>{cleanup();const b=this.box;this.box=null;box.remove();if(!b)return;const a=this.clientToWorld(r.left+Math.min(b.start.x,b.current.x),r.top+Math.min(b.start.y,b.current.y)),z=this.canvas.view.zoom,sel={x:a.x,y:a.y,w:Math.abs(b.current.x-b.start.x)/z,h:Math.abs(b.current.y-b.start.y)/z},hidden=Graph.hiddenByCollapse(this.canvas);this.canvasSelection.clear();for(const[id,p]of Object.entries(this.canvas.canvasPlacements)){if(hidden.has(id))continue;const nr=Geo.nodeRect(p);if(nr.x>=sel.x&&nr.y>=sel.y&&nr.x+nr.w<=sel.x+sel.w&&nr.y+nr.h<=sel.y+sel.h)this.canvasSelection.add(id);}this.render();},cancel=()=>{cleanup();this.box?.el?.remove();this.box=null;this.render();};this.box.cleanup=cleanup;window.addEventListener('pointermove',move,true);window.addEventListener('pointerup',up,true);window.addEventListener('pointercancel',cancel,true);return;}
      this.canvasSelection.clear();this.memoSelection.clear();this.syncSelectionUi();const start={x:e.clientX,y:e.clientY,panX:this.canvas.view.panX,panY:this.canvas.view.panY};const cleanup=()=>{window.removeEventListener('pointermove',move,true);window.removeEventListener('pointerup',up,true);window.removeEventListener('pointercancel',cancel,true);},move=ev=>{if(!this.pan)return;ev.preventDefault();ev.stopPropagation();const z=this.canvas.view.zoom;this.canvas.view.panX=start.panX-(ev.clientX-start.x)/z;this.canvas.view.panY=start.panY-(ev.clientY-start.y)/z;this.clampPan(false);},up=()=>{cleanup();if(!this.pan)return;this.pan=null;this.persistView();},cancel=()=>{cleanup();if(this.pan){this.canvas.view.panX=start.panX;this.canvas.view.panY=start.panY;this.pan=null;}this.applyTransform();};this.pan={...start,cleanup};window.addEventListener('pointermove',move,true);window.addEventListener('pointerup',up,true);window.addEventListener('pointercancel',cancel,true);
    }
    onWheel(e){if(!this.canvas)return;e.preventDefault();e.stopPropagation();if(!e.ctrlKey)return;this.activity();const rect=this.canvasWrap.getBoundingClientRect(),old=this.canvas.view.zoom,local={x:e.clientX-rect.left,y:e.clientY-rect.top},world={x:this.canvas.view.panX+local.x/old,y:this.canvas.view.panY+local.y/old},factor=e.deltaY<0?1.1:1/1.1,nz=U.clamp(old*factor,C.MIN_ZOOM,C.MAX_ZOOM);this.canvas.view.zoom=nz;this.canvas.view.panX=world.x-local.x/nz;this.canvas.view.panY=world.y-local.y/nz;this.clampPan(false);this.updateToolbar();clearTimeout(this._zoomSave);this._zoomSave=setTimeout(()=>this.persistView(),180);}
    resetZoomAndCenter(){if(!this.canvas)return;const visible=Object.entries(this.canvas.canvasPlacements).filter(([id])=>!Graph.hiddenByCollapse(this.canvas).has(id));let center={x:C.WORLD_W/2,y:C.WORLD_H/2};if(visible.length){const rs=visible.map(([,p])=>Geo.nodeRect(p)),minX=Math.min(...rs.map(r=>r.x)),maxX=Math.max(...rs.map(r=>r.x+r.w)),minY=Math.min(...rs.map(r=>r.y)),maxY=Math.max(...rs.map(r=>r.y+r.h));center={x:(minX+maxX)/2,y:(minY+maxY)/2};}this.canvas.view.zoom=C.DEFAULT_ZOOM;const vw=this.canvasWrap.clientWidth/C.DEFAULT_ZOOM,vh=this.canvasWrap.clientHeight/C.DEFAULT_ZOOM;this.canvas.view.panX=center.x-vw/2;this.canvas.view.panY=center.y-vh/2;this.clampPan(false);this.render();this.persistView();}
    async toggleCollapse(id){await this.mutate(c=>{c.canvasPlacements[id].subtreeCollapsed=!c.canvasPlacements[id].subtreeCollapsed;return true;},{history:false});}
    onEdgeDoubleClick(e,eid){e.preventDefault();e.stopPropagation();const p=this.clientToWorld(e.clientX,e.clientY),edge=this.canvas.relations[eid],path=this.routes[eid],tol=Math.max(2,4/this.canvas.view.zoom);if(edge&&path&&Router.sharedTrunkAt(this.canvas,this.routes,eid,p,tol)){UI.toast(C.MESSAGES.CANNOT_DELETE_SHARED);return;}this.mutate(c=>{delete c.relations[eid];return true;});}
    jumpToAnchor(id){const ent=this.canvas.entities[id];if(!ent?.anchor){this.memoSelection.clear();this.selectionArea='canvas';this.canvasSelection.clear();this.canvasSelection.add(id);this.render();return;}const loc=Chat.scrollAnchor(ent.anchor);if(!loc.ok){ent.anchorStatus='missing';this.render();this.persistView();UI.toast(C.MESSAGES.ANCHOR_MISSING);return;}ent.anchorStatus=loc.status==='exact'?'ok':'message';this.render();this.persistView();if(loc.status==='message')UI.toast(C.MESSAGES.ANCHOR_MESSAGE_ONLY);this.flashId=id;this.renderHighlightsSoon();setTimeout(()=>{this.flashId=null;this.renderHighlightsSoon();},1800);}
    renderHighlightsSoon(){if(this.sleeping||!this.canvas)return;clearTimeout(this._hlTimer);this._hlTimer=setTimeout(()=>{if(!this.canvas||this.sleeping)return;const anchors=Object.values(this.canvas.entities).filter(e=>e.anchor).map(e=>({entityId:e.entityId,anchor:e.anchor,color:e.color})),statuses=this.highlights?.render(anchors,this.flashId)||{};let changed=false;for(const [id,status] of Object.entries(statuses||{})){const e=this.canvas.entities[id];if(e?.anchor&&e.anchorStatus!==status){e.anchorStatus=status;changed=true;}}if(changed){this.syncAnchorStatusUi();clearTimeout(this._anchorStatusSave);this._anchorStatusSave=setTimeout(()=>this.persistView(),300);}},140);}
    reverseLocate(ids){if(!this.canvas||!ids.length)return;if(ids.length===1){this.locateEntity(ids[0]);return;}UI.modal('选择对应 ChatGPT NET 内容',(p,close)=>{ids.forEach(id=>{const e=this.canvas.entities[id];if(!e)return;const b=UI.el('button','cgn-result',e.text);b.onclick=()=>{close();this.locateEntity(id);};p.append(b);});});}
    locateEntity(id){if(this.canvas.canvasPlacements[id]){for(const[pId,p]of Object.entries(this.canvas.canvasPlacements))if(p.subtreeCollapsed&&Graph.descendants(this.canvas,pId).has(id))p.subtreeCollapsed=false;const p=this.canvas.canvasPlacements[id],v=this.viewportWorld();this.canvas.view.panX=p.x+p.width/2-v.w/2;this.canvas.view.panY=p.y+p.height/2-v.h/2;this.clampPan(false);this.canvasSelection.clear();this.canvasSelection.add(id);this.memoSelection.clear();this.render();this.persistView();}else if(this.canvas.memoPlacements[id]){const sid=this.canvas.memoPlacements[id].sectionId;if(sid&&this.canvas.memoSections[sid]?.collapsed)this.canvas.memoSections[sid].collapsed=false;this.memoSelection.clear();this.memoSelection.add(id);this.canvasSelection.clear();this.render();setTimeout(()=>this.memoList.querySelector(`[data-id="${CSS.escape(id)}"]`)?.scrollIntoView({block:'center'}));this.persistView();}}
    async deleteSelected(){if(!this.canvas)return;if(this.canvasSelection.size){const ids=[...this.canvasSelection],ok=await this.mutate(c=>{for(const id of ids){delete c.canvasPlacements[id];delete c.entities[id];Graph.removeEntityEdges(c,id);}this.endAutoGroupIfTouched(c,ids);return true;});if(ok)this.canvasSelection.clear();}else if(this.memoSelection.size){const ids=[...this.memoSelection],ok=await this.mutate(c=>{for(const id of ids){delete c.memoPlacements[id];delete c.entities[id];c.memoOrder=(c.memoOrder||[]).filter(t=>t!==`e:${id}`);for(const sec of Object.values(c.memoSections))sec.itemIds=(sec.itemIds||[]).filter(x=>x!==id);}return true;});if(ok)this.memoSelection.clear();}this.syncSelectionUi();}
    async unlinkSelected(){if(!this.canvasSelection.size)return;const ids=new Set(this.canvasSelection);await this.mutate(c=>{for(const[eid,e]of Object.entries(c.relations))if(ids.has(e.childId))delete c.relations[eid];this.endAutoGroupIfTouched(c,[...ids]);return true;});}
    async applyColorSlot(i){if(!this.canvas)return;const has=this.canvasSelection.size||this.memoSelection.size;await this.mutate(c=>{c.view.activeColorSlot=i;if(has){const color=StoreRuntime.colorsFor(c)[i],ids=this.canvasSelection.size?[...this.canvasSelection]:[...this.memoSelection];ids.forEach(id=>{if(c.entities[id])c.entities[id].color=color;});}return true;},{history:!!has,validateRoutes:false});}
    openColorSettings(){if(!this.canvas)return;const idx=this.canvas.view.activeColorSlot,colors=StoreRuntime.colorsFor(this.canvas),current=colors[idx];UI.modal(`颜色槽 ${idx+1}`,(p,close)=>{const row=UI.el('div','cgn-row'),picker=document.createElement('input');picker.type='color';picker.value=current;const text=document.createElement('input');text.type='text';text.value=current;text.placeholder='#RRGGBB 或 R,G,B';row.append(picker,text);p.append(row);picker.oninput=()=>text.value=picker.value.toUpperCase();const scope=UI.el('div','cgn-row'),conv=UI.el('button','cgn-btn','当前对话'),global=UI.el('button','cgn-btn','全局默认');scope.append(conv,global);p.append(scope);const apply=async which=>{const val=U.normalizeRgb(text.value);if(!val){UI.toast('请输入有效的 RGB 颜色。');return;}close();if(which==='conversation'){await this.mutate(c=>{if(!c.colorOverride)c.colorOverride=[...StoreRuntime.colorsFor(c)];c.colorOverride[idx]=val;return true;},{history:false,validateRoutes:false});}else{const g=U.deepClone(this.global);g.colorSlots[idx]=val;try{this.global=await Store.saveGlobal(g);this.render();}catch{UI.toast(C.MESSAGES.SAVE_FAILED);}}};conv.onclick=()=>apply('conversation');global.onclick=()=>apply('global');});}
    async toMemo(ids){const ok=await this.mutate(c=>{for(const id of ids){if(!c.canvasPlacements[id])continue;delete c.canvasPlacements[id];Graph.removeEntityEdges(c,id);c.memoPlacements[id]={entityId:id,sectionId:null};c.memoOrder=(c.memoOrder||[]).filter(t=>t!==`e:${id}`);c.memoOrder.push(`e:${id}`);}this.endAutoGroupIfTouched(c,ids);return true;});if(ok){this.canvasSelection.clear();this.memoSelection=new Set(ids);this.selectionArea='memo';this.syncSelectionUi();}return ok;}
    onMemoClick(e,id){e.stopPropagation();if(e.shiftKey&&this.canvas.entities[id]?.anchor){this.canvasSelection.clear();this.selectionArea='memo';this.jumpToAnchor(id);return;}this.canvasSelection.clear();this.selectionArea='memo';if(e.ctrlKey){this.memoSelection.has(id)?this.memoSelection.delete(id):this.memoSelection.add(id);}else{this.memoSelection.clear();this.memoSelection.add(id);}this.syncSelectionUi();}
    memoDragIds(id){if(this.memoSelection.has(id)&&this.memoSelection.size)return [...this.memoSelection];this.memoSelection=new Set([id]);this.canvasSelection.clear();this.selectionArea='memo';return[id];}
    onMemoDragStart(e,id){const ids=this.memoDragIds(id);e.dataTransfer.setData('application/x-chatgpt-net-memo',JSON.stringify(ids));e.dataTransfer.effectAllowed='move';const ghost=UI.el('div','cgn-ghost',ids.length>1?`${ids.length} 个备忘录条目`:this.canvas.entities[id]?.text||'条目');document.body.append(ghost);e.dataTransfer.setDragImage(ghost,10,10);setTimeout(()=>ghost.remove(),0);}
    onSectionDragStart(e,sid){e.dataTransfer.setData('application/x-chatgpt-net-section',sid);e.dataTransfer.effectAllowed='move';}
    readMemoIds(e){try{return JSON.parse(e.dataTransfer.getData('application/x-chatgpt-net-memo')||'[]');}catch{return[];}}
    async onMemoDropToCanvas(e){e.preventDefault();const ids=this.readMemoIds(e);if(!ids.length)return;const center=this.clientToWorld(e.clientX,e.clientY);await this.memoToCanvas(ids,center);}
    async memoToCanvas(ids,center){
      const ordered=this.memoVisualOrder(ids),temp=U.deepClone(this.canvas),width=this.newNodeWidth();if(!width){UI.toast(C.MESSAGES.CANNOT_PLACE);return;}const solution=this.memoPlacementSolution(temp,ordered,center,width);if(!solution){UI.toast(C.MESSAGES.CANNOT_PLACE);return;}
      const ok=await this.mutate(c=>{for(const[id,p]of Object.entries(solution.shifted))if(c.canvasPlacements[id]){c.canvasPlacements[id].x=p.x;c.canvasPlacements[id].y=p.y;}for(const id of ordered){delete c.memoPlacements[id];c.memoOrder=(c.memoOrder||[]).filter(t=>t!==`e:${id}`);for(const sec of Object.values(c.memoSections))sec.itemIds=(sec.itemIds||[]).filter(x=>x!==id);c.canvasPlacements[id]={entityId:id,x:solution.positions[id].x,y:solution.positions[id].y,width,height:this.measureNodeHeight(c.entities[id].text,width,c.entities[id].kind),subtreeCollapsed:false};}return true;});if(ok){this.memoSelection.clear();this.canvasSelection=new Set(ordered);this.selectionArea='canvas';this.syncSelectionUi();}
    }
    memoVisualOrder(ids){const set=new Set(ids),out=[];for(const token of this.canvas.memoOrder||[]){if(token.startsWith('e:')){const id=token.slice(2);if(set.has(id))out.push(id);}else if(token.startsWith('s:')){const sec=this.canvas.memoSections[token.slice(2)];for(const id of sec?.itemIds||[])if(set.has(id))out.push(id);}}for(const id of ids)if(!out.includes(id))out.push(id);return out;}
    layoutGroupNear(c,ids,center,width){const gap=C.NODE_GAP,v=this.viewportWorld(),maxCols=Math.max(1,Math.floor((v.w+gap)/(width+gap))),cols=Math.min(maxCols,Math.max(1,ids.length)),positions={},heights=ids.map(id=>this.measureNodeHeight(c.entities[id].text,width,c.entities[id].kind)),rowHeights=[];for(let r=0;r<Math.ceil(ids.length/cols);r++)rowHeights[r]=Math.max(...heights.slice(r*cols,(r+1)*cols));const totalH=rowHeights.reduce((a,h)=>a+h,0)+gap*Math.max(0,rowHeights.length-1);let y=center.y-totalH/2;ids.forEach((id,i)=>{const r=Math.floor(i/cols),count=Math.min(cols,ids.length-r*cols),rowW=count*width+(count-1)*gap,x0=center.x-rowW/2;positions[id]={x:x0+(i%cols)*(width+gap),y};c.canvasPlacements[id]={entityId:id,x:positions[id].x,y:positions[id].y,width,height:heights[i],subtreeCollapsed:false};if(i%cols===count-1)y+=rowHeights[r]+gap;});const pos=this.findRouteLegalPositions(c,ids,positions);ids.forEach(id=>delete c.canvasPlacements[id]);return pos;}
    memoPlacementSolution(temp,ids,center,width){const original={};for(const[id,p]of Object.entries(temp.canvasPlacements))original[id]={x:p.x,y:p.y};for(let attempt=0;attempt<80;attempt++){const positions=this.layoutGroupNear(temp,ids,center,width);if(positions){const shifted={};for(const[id,p]of Object.entries(temp.canvasPlacements))if(original[id]&&(p.x!==original[id].x||p.y!==original[id].y))shifted[id]={x:p.x,y:p.y};return{positions,shifted};}const entries=Object.entries(temp.canvasPlacements);if(!entries.length)break;const dy=Math.min(48,...entries.map(([,p])=>p.y));if(!(dy>0))break;for(const[,p]of entries)p.y-=dy;}return null;}
    async dropMemoToSection(e,sid){e.preventDefault();e.stopPropagation();const ids=this.readMemoIds(e);if(!ids.length)return;const ordered=this.memoVisualOrder(ids);await this.mutate(c=>{const sec=c.memoSections[sid];if(!sec)return false;for(const id of ordered){const old=c.memoPlacements[id]?.sectionId;if(old&&c.memoSections[old])c.memoSections[old].itemIds=(c.memoSections[old].itemIds||[]).filter(x=>x!==id);c.memoOrder=(c.memoOrder||[]).filter(t=>t!==`e:${id}`);c.memoPlacements[id].sectionId=sid;}sec.itemIds=(sec.itemIds||[]).filter(x=>!ids.includes(x));sec.itemIds.push(...ordered);return true;});}
    async dropMemoUngrouped(e){e.preventDefault();const ids=this.readMemoIds(e);if(ids.length){const ordered=this.memoVisualOrder(ids);await this.mutate(c=>{for(const id of ordered){const old=c.memoPlacements[id]?.sectionId;if(old&&c.memoSections[old])c.memoSections[old].itemIds=(c.memoSections[old].itemIds||[]).filter(x=>x!==id);c.memoPlacements[id].sectionId=null;c.memoOrder=(c.memoOrder||[]).filter(t=>t!==`e:${id}`);c.memoOrder.push(`e:${id}`);}return true;});return;}const sid=e.dataTransfer.getData('application/x-chatgpt-net-section');if(sid)await this.reorderSection(sid,null);}
    async dropMemoBeforeSection(e,sid){e.preventDefault();e.stopPropagation();const ids=this.readMemoIds(e);if(!ids.length)return;const ordered=this.memoVisualOrder(ids);await this.mutate(c=>{for(const id of ordered){const old=c.memoPlacements[id]?.sectionId;if(old&&c.memoSections[old])c.memoSections[old].itemIds=(c.memoSections[old].itemIds||[]).filter(x=>x!==id);c.memoPlacements[id].sectionId=null;}let order=(c.memoOrder||[]).filter(t=>!ids.some(id=>t===`e:${id}`)),idx=order.indexOf(`s:${sid}`);if(idx<0)idx=order.length;order.splice(idx,0,...ordered.map(id=>`e:${id}`));c.memoOrder=order;return true;},{validateRoutes:false});}
    async dropMemoBefore(e,targetId){e.preventDefault();e.stopPropagation();const ids=this.readMemoIds(e);if(!ids.length||ids.includes(targetId))return;const ordered=this.memoVisualOrder(ids);await this.mutate(c=>{const targetMp=c.memoPlacements[targetId],section=targetMp?.sectionId;if(section){const arr=c.memoSections[section].itemIds||[];for(const id of ordered){const old=c.memoPlacements[id]?.sectionId;if(old&&c.memoSections[old])c.memoSections[old].itemIds=(c.memoSections[old].itemIds||[]).filter(x=>x!==id);c.memoOrder=(c.memoOrder||[]).filter(t=>t!==`e:${id}`);c.memoPlacements[id].sectionId=section;}const clean=arr.filter(x=>!ids.includes(x)),idx=clean.indexOf(targetId);clean.splice(Math.max(0,idx),0,...ordered);c.memoSections[section].itemIds=clean;}else{for(const id of ordered){const old=c.memoPlacements[id]?.sectionId;if(old&&c.memoSections[old])c.memoSections[old].itemIds=(c.memoSections[old].itemIds||[]).filter(x=>x!==id);c.memoPlacements[id].sectionId=null;}let order=(c.memoOrder||[]).filter(t=>!ids.includes(t.slice(2))),idx=order.indexOf(`e:${targetId}`);order.splice(Math.max(0,idx),0,...ordered.map(id=>`e:${id}`));c.memoOrder=order;}return true;});}
    beginNewSection(){const input=document.createElement('input');input.type='text';input.placeholder='分隔标题';input.className='cgn-memo-item';this.memoList.prepend(input);input.focus();let done=false;const finish=async commit=>{if(done)return;done=true;const title=input.value.trim();input.remove();if(commit&&title)await this.mutate(c=>{const sid=U.uuid();c.memoSections[sid]={sectionId:sid,title,collapsed:false,itemIds:[],createdAt:U.now(),modifiedAt:U.now()};c.memoOrder=(c.memoOrder||[]);c.memoOrder.unshift(`s:${sid}`);return true;});};input.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();finish(true);}if(e.key==='Escape'){e.preventDefault();finish(false);}};input.onblur=()=>finish(true);}
    async renameSection(sid,title){await this.mutate(c=>{c.memoSections[sid].title=title;c.memoSections[sid].modifiedAt=U.now();return true;});}
    async toggleMemoSection(sid){await this.mutate(c=>{c.memoSections[sid].collapsed=!c.memoSections[sid].collapsed;return true;},{history:false,validateRoutes:false});}
    async deleteSection(sid){await this.mutate(c=>{const sec=c.memoSections[sid];if(!sec)return false;const token=`s:${sid}`,idx=(c.memoOrder||[]).indexOf(token);c.memoOrder=(c.memoOrder||[]).filter(t=>t!==token);const inserts=[];for(const id of sec.itemIds||[]){if(c.memoPlacements[id])c.memoPlacements[id].sectionId=null;inserts.push(`e:${id}`);}c.memoOrder.splice(Math.max(0,idx),0,...inserts);delete c.memoSections[sid];return true;},{validateRoutes:false});}
    async reorderSection(sid,beforeSid){await this.mutate(c=>{let o=(c.memoOrder||[]).filter(t=>t!==`s:${sid}`);const idx=beforeSid?o.indexOf(`s:${beforeSid}`):-1;if(idx>=0)o.splice(idx,0,`s:${sid}`);else o.push(`s:${sid}`);c.memoOrder=o;return true;},{validateRoutes:false});}
    openSearch(){if(!this.canvas)return;UI.modal('搜索当前对话',(p,close)=>{const row=UI.el('div','cgn-row'),input=document.createElement('input');input.type='search';input.placeholder='输入普通文字';row.append(input);p.append(row);const results=UI.el('div','cgn-results');p.append(results);const run=()=>{results.replaceChildren();const q=input.value.toLowerCase();if(!q)return;for(const e of Object.values(this.canvas.entities)){const hay=`${e.text}\n${e.originalText||''}`.toLowerCase();if(hay.includes(q)){const b=UI.el('button','cgn-result',e.text);b.onclick=()=>{close();this.locateEntity(e.entityId);};results.append(b);}}for(const sec of Object.values(this.canvas.memoSections)){if(sec.title.toLowerCase().includes(q)){const b=UI.el('button','cgn-result',`备忘录标题：${sec.title}`);b.onclick=()=>{close();if(sec.collapsed)sec.collapsed=false;this.render();setTimeout(()=>this.memoList.querySelector(`[data-section-id="${CSS.escape(sec.sectionId)}"]`)?.scrollIntoView({block:'center'}));this.persistView();};results.append(b);}}};input.oninput=run;input.focus();});}
    openSettings(){UI.modal('ChatGPT NET 设置',(p,close)=>{const note=UI.el('div','','备份文件包含 ChatGPT 对话摘录和正文定位信息。导出文件由 Firefox 保存到浏览器下载位置；扩展不会宣称可移动 Firefox 内部数据库。');note.style.marginBottom='10px';p.append(note);const row=UI.el('div','cgn-row'),cur=UI.el('button','cgn-btn','导出当前画布'),all=UI.el('button','cgn-btn','导出全部画布'),imp=UI.el('button','cgn-btn','导入备份');row.append(cur,all,imp);p.append(row);cur.onclick=()=>{if(!this.canvas)return;if(!confirm('备份文件包含 ChatGPT 对话摘录和正文定位信息。继续导出当前画布？'))return;U.downloadJson(`chatgpt-net-${this.canvas.conversationId}.json`,Schema.exportBundle([this.canvas],this.global));};all.onclick=async()=>{if(!confirm('备份文件包含 ChatGPT 对话摘录和正文定位信息。继续导出全部画布？'))return;if(this.canvas&&!this.conflict)await this.persistView();const r=await Store.exportAll();U.downloadJson('chatgpt-net-all.json',r.bundle);};imp.onclick=()=>this.importBackup(close);});}
    importBackup(close){const input=document.createElement('input');input.type='file';input.accept='.json,application/json';input.onchange=async()=>{const f=input.files?.[0];if(!f)return;let b;try{b=JSON.parse(await f.text());if(!b||b.product!==C.PRODUCT||!C.IMPORT_BASELINES.includes(b.baseline)||b.schemaVersion!==C.SCHEMA_VERSION||!Array.isArray(b.canvases)||new Set(b.canvases.map(c=>c.conversationId)).size!==b.canvases.length||!b.canvases.every(c=>Schema.validateCanvas(c)&&Router.routeAll(c).ok)||(b.global&&!Schema.validateGlobal(b.global)))throw new Error();}catch{UI.toast('导入失败：文件损坏、存在非法布局或格式不受支持。现有数据未被修改。');return;}const decisions={};if(b.global)decisions.__global=confirm('备份包含全局默认颜色、侧栏宽度和画布/备忘录比例。\n确定：使用备份中的全局默认设置\n取消：保留当前全局默认设置')?'imported':'existing';for(const c of b.canvases){const existing=await Store.loadCanvas(c.conversationId);if(existing)decisions[c.conversationId]={choice:confirm(`对话 ${c.title||c.conversationId} 已有画布。\n确定：保留导入文件中的完整版本\n取消：保留现有完整版本`)?'imported':'existing',expectedRevision:existing.revision};else decisions[c.conversationId]={choice:'imported',expectedRevision:null};}try{await Store.importBundle(b,decisions);close();if(this.canvas&&decisions[this.canvas.conversationId]?.choice==='imported')await this.loadConversation(this.canvas.conversationId);UI.toast('导入完成。');}catch{UI.toast('导入失败，现有数据未被修改。');}};input.click();}
    startSplit(e){if(!this.canvas)return;e.preventDefault();const start=e.clientY,ratio=this.canvas.view.memoRatio,rect=this.main.getBoundingClientRect();const cleanup=()=>{window.removeEventListener('pointermove',move,true);window.removeEventListener('pointerup',up,true);window.removeEventListener('pointercancel',cancel,true);},move=ev=>{if(!this.splitDrag)return;const dy=ev.clientY-start;this.canvas.view.memoRatio=U.clamp(ratio-dy/rect.height,C.MIN_MEMO_RATIO,C.MAX_MEMO_RATIO);this.applyPaneRatio();},up=()=>{if(!this.splitDrag){cleanup();return;}cleanup();this.splitDrag=null;const g=U.deepClone(this.global);g.memoRatio=this.canvas.view.memoRatio;Store.saveGlobal(g).then(saved=>{this.global=saved;}).catch(()=>UI.toast(C.MESSAGES.SAVE_FAILED));this.persistView();},cancel=()=>{if(this.splitDrag){this.canvas.view.memoRatio=ratio;this.splitDrag=null;}cleanup();this.applyPaneRatio();};this.splitDrag={ratio,cleanup};window.addEventListener('pointermove',move,true);window.addEventListener('pointerup',up,true);window.addEventListener('pointercancel',cancel,true);}
    startSidebarResize(e){if(!this.canvas)return;e.preventDefault();const width=this.canvas.view.sidebarWidth,cleanup=()=>{window.removeEventListener('pointermove',move,true);window.removeEventListener('pointerup',up,true);window.removeEventListener('pointercancel',cancel,true);},move=ev=>{if(!this.sidebarDrag)return;const w=U.clamp(innerWidth-ev.clientX,C.MIN_SIDEBAR_W,C.MAX_SIDEBAR_W);this.canvas.view.sidebarWidth=w;this.sidebar.style.width=`${w}px`;this.clampPan(false);},up=()=>{if(!this.sidebarDrag){cleanup();return;}cleanup();this.sidebarDrag=null;UI.reservePage(this.canvas.view.sidebarWidth,true);this.renderHighlightsSoon();this.global.sidebarWidth=this.canvas.view.sidebarWidth;Store.saveGlobal(this.global).catch(()=>UI.toast(C.MESSAGES.SAVE_FAILED));this.persistView();},cancel=()=>{if(this.sidebarDrag){this.canvas.view.sidebarWidth=width;this.canvas.view.panX=this.sidebarDrag.panX;this.canvas.view.panY=this.sidebarDrag.panY;this.sidebar.style.width=`${width}px`;UI.reservePage(width,true);this.sidebarDrag=null;}cleanup();this.applyTransform();this.renderHighlightsSoon();};this.sidebarDrag={width,panX:this.canvas.view.panX,panY:this.canvas.view.panY,cleanup};window.addEventListener('pointermove',move,true);window.addEventListener('pointerup',up,true);window.addEventListener('pointercancel',cancel,true);}
    onKeyDown(e){if(!this.enabled||!this.mounted||U.isEditable(e.target))return;if(e.key==='Escape'){if(this.drag||this.resize||this.box||this.pan||this.splitDrag||this.sidebarDrag){this.cancelTemporary();e.preventDefault();return;}this.canvasSelection.clear();this.memoSelection.clear();this.selectionPopup?.hide();this.syncSelectionUi();return;}if(e.ctrlKey&&!e.altKey&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?this.redo():this.undo();}}
  }

  const app=new App();NS.app=app;app.init().catch(e=>{console.error('[ChatGPT NET] initialization failed',e);UI.toast('ChatGPT NET 初始化失败。');});
})();
